### ISSUE TITLE
Operator should support DeploymentConfigs out of the box

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#1025]
### What is the environment (Minikube, Openshift)?

OpenShift

### What is the SBO version used?

0.10.0

### What are the steps to reproduce this issue?
  1.  Create DeploymentConfig
  2. Try to bind to Deployment config
  3. 
  ```
  conditions:
    - lastTransitionTime: '2021-09-17T13:34:12Z'
      message: ''
      reason: DataCollected
      status: 'True'
      type: CollectionReady
    - lastTransitionTime: '2021-09-17T13:34:12Z'
      message: >-
        cannot find application resources for the given reference:
        deploymentconfigs.apps.openshift.io "example" is forbidden: User
        "system:serviceaccount:openshift-operators:service-binding-operator"
        cannot get resource "deploymentconfigs" in API group "apps.openshift.io"
        in the namespace "wtrocki"
      reason: ApplicationNotFound
      status: 'False'
      type: InjectionReady
    - lastTransitionTime: '2021-09-17T13:34:12Z'
      message: >-
        cannot find application resources for the given reference:
        deploymentconfigs.apps.openshift.io "example" is forbidden: User
        "system:serviceaccount:openshift-operators:service-binding-operator"
        cannot get resource "deploymentconfigs" in API group "apps.openshift.io"
        in the namespace "wtrocki"
      reason: ProcessingError
      status: 'False'
      type: Ready

```

**Comment by pedjak** [comment]
Thanks for the report. While here - is there any other OpenShift resource that we should support out of the box?

**Comment by wtrocki** [comment]
DeploymentConfig covers 99% of cases. 
Worth to mention that deploymentConfig is also harder to work with as after applying binding we need to create new rollout to see changes.

**Comment by pedjak** [comment]
> DeploymentConfig covers 99% of cases.

Just to verify if I got it correct: `DeploymentConfig` is application in service binding case? Or a service?

**Comment by wtrocki** [comment]
Always Application. Same like Deployment

**Comment by mezarin** [comment]
Similarly, when linking the app to Kafka:

```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
...
spec:
  application:
    group: apps
    name: kafka-app
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
    - group: kafka.strimzi.io
      kind: Kafka
      name: kafka
      version: v1beta2
status:
  conditions:
    - lastTransitionTime: '2021-09-21T13:55:44Z'
      message: >-
        kafkas.kafka.strimzi.io "kafka" is forbidden: User
        "system:serviceaccount:openshift-operators:service-binding-operator"
        cannot get resource "kafkas" in API group "kafka.strimzi.io" in the
        namespace "service-binding-demo"
      reason: ProcessingError
      status: 'False'
      type: Ready
    - lastTransitionTime: '2021-09-21T13:55:44Z'
      message: >-
        kafkas.kafka.strimzi.io "kafka" is forbidden: User
        "system:serviceaccount:openshift-operators:service-binding-operator"
        cannot get resource "kafkas" in API group "kafka.strimzi.io" in the
        namespace "service-binding-demo"
      reason: ErrorReadingServices
      status: 'False'
      type: CollectionReady
  secret: ''
```
