### ISSUE TITLE
Binding to an Opstree Solutions Redis instance with no redisSecret fails

### ISSUE THREAD

**Issue by feloy** [redhat-developer/service-binding-operator#1088]
### What is the environment (Minikube, Openshift)?

CodeReady Containers version: 1.37.0+3876d27d
OpenShift version: 4.9.10 (embedded in executable)

### What is the SBO version used?

v1.0.0

### What are the steps to reproduce this issue?

  1. Create a redis operator with the following specs:

```
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis1
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
    serviceType: ClusterIP
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

  2. Create a link with the specs:

```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: redis-binding
spec:
  application:
    group: apps
    name: my-deployment
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
  - group: redis.redis.opstreelabs.in
    id: redis1
    kind: Redis
    name: redis1
    version: v1beta1
```

### What is the expected behaviour?

The service binding operator should create the binding

### What is the actual behaviour?

The creation of the binding fails due to a not found `redisSecret` field.

The `redisSecret` is not mandatory in the `redis` CRD.

```
status:
  conditions:
  - lastTransitionTime: "2022-01-10T13:55:02Z"
    message: redisSecret is not found
    reason: ErrorReadingBinding
    status: "False"
    type: CollectionReady
  - lastTransitionTime: "2022-01-10T13:55:02Z"
    message: redisSecret is not found
    reason: ProcessingError
    status: "False"
    type: Ready
  secret: ""
```

```
$ kubectl get crd redis.redis.redis.opstreelabs.in -o yaml 
[...]
    service.binding/host: path={.metadata.name}
    service.binding/password: path={.spec.kubernetesConfig.redisSecret.name},objectType=Secret,sourceKey=password
    service.binding/type: redis
[...]
```

### Service Binding Operator Logs

```
{"level":"info","ts":1641823073.7587097,"logger":"controllers.ServiceBinding","msg":"Reconciling","serviceBinding":"prj1/nodejs-x5314-oasw-redis-redis1"}
{"level":"info","ts":1641823073.8065016,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"prj1/nodejs-x5314-oasw-redis-redis1","retry":true,"error":"redisSecret is not found"}
{"level":"error","ts":1641823073.806546,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding","name":"nodejs-x5314-oasw-redis-redis1","namespace":"prj1","error":"redisSecret is not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
```

## Release Notes
Currently, binding to a `Redis` CR from the `redis.redis.opstreelabs.in/v1beta1` API fails due to the absence of an optional `redisSecret` field in the `Redis` CR. There is currently no workaround for this issue.
