### ISSUE TITLE
Feedback: Handle Backing Services whose CRs link to Secrets/ConfigMaps using CR name-based conventions

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#112]
Backing services such as the ElasticSearch elastic-cloud operator (https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/elastic-cloud) have a CR that links to Secrets/ConfigMaps using the CR name as a common prefix. As described here: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-accessing-elastic-services.html#k8s-request-elasticsearch-endpoint, in order to bind to the service endpoint for the Elasticsearch CR, the following secrets must be accessed: 

> $NAME-es-http-certs-public - to retrieve the CA Certificate with key "tls.crt"
> $NAME-es-elastic-user - to retrieve the password of the elastic user with key "elastic"

These secrets are identified via the common CR name prefix "$NAME" followed by well-known suffixes for specific secrets. This is a common pattern used by other operators as well. In the case of the strimzi-kafka-operator KafkaUser CR (https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/strimzi-kafka-operator) (https://strimzi.io/docs/master/#proc-creating-kafka-user-tls-using-uo), the same name is used for the KafkaUser credentials Secret as the KafkaUser CR itself.

The service-binding-operator should support backing services whose CRs link to Secrets/ConfigMaps using CR name-based conventions. Backing service operator maintainers should not be required to modify their CRDs to support the service-binding-operator. Rather, they should only need to add annotations to the ClusterServiceVersion for their backing service operator to be accessible by the service-binding-operator.

**Comment by sbose78** [comment]
> Rather, they should only need to add annotations to the ClusterServiceVersion for their backing service operator to be accessible by the service-binding-operator.

Agreed, that's my stand as well :)


> The service-binding-operator should support backing services whose CRs link to Secrets/ConfigMaps using CR name-based conventions. 

@ron1  , Are you suggesting that if there's a configmap/secret that is _owned_ by the CR and uses the same naming convention, we consume that as 'interesting to bind' as well - irrespective of whether annotations were added for such objects in the csv?

**Comment by ron1** [comment]
How would interesting configmaps/secrets be identified for annotation in the CVS? No path exists from the CR since the link is via naming convention.

**Comment by sbose78** [comment]
I really like the idea - let me think over it and come up with an end to end picture of this.

**Comment by ron1** [comment]
@sbose78 As described here (https://github.com/redhat-developer/service-binding-operator/pull/159#discussion_r321761887), I agree it makes sense for the operator to support binding to backing services that do not have OLM Annotations. I have revised my proposed POC accordingly. The revised schema is simpler and introduces the ability to transform resources that are not Secrets. The sample also includes a bit more evolved Kafka example. See below and let me know your thoughts.

```
backingServiceExtractors:
- resourceSelector:
    group: kafka.strimzi.io
    version: v1beta1
    kind: Kafka
    resourceRef: my-cluster
  resourceToSecretTransforms: # keys/values are auto-added if source is ConfigMap or Secret
  - addKey:
    key: "bootstrap.servers"
    jsonPathExpression: "{.status.listeners[?(@.type=\"tls\")]}{range .addresses[*]}{.host}:{.port}, {end}"
  - renameKey: #example
    from: "special-key-1"
    to: "my-new-special-key-1"
  - removeKey: #example
    key: "special-key-2"
- resourceSelector:
    group: null
    version: v1
    kind: Secret
    resourceRef: my-cluster-clients-ca-cert
  resourceToSecretTransforms:
  - renameKey:
    from: "ca.crt"
    to: "clients-ca.crt"
- resourceSelector:
    group: kafka.strimzi.io
    version: v1beta1
    kind: KafkaUser
    resourceRef: my-user
  resourceToSecretTransforms:
  - addKey:
    key: "username"
    jsonPathExpression: ".status.username"
- resourceSelector: # no transforms needed since password is auto-added from Secret
    group: null
    version: v1
    kind: Secret
    resourceRef: my-user
applicationInjector:
  resourceSelector:
    matchLabels:
      connects-to: postgres
      environment: demo
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    resourceRef: deploymentconfigs
  resourceToSecretTransforms:
  - addKey:
    key: "consumer-ssl.properties"
    jsonPathExpression: "bootstrap.servers={.bootstrap.servers}\nsecurity.protocol=SASL_SSL\nsasl.mechanism=PLAIN\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \ username=\"{.username}\" \ password=\"{.password}\";}"
  injectAsVolumeMount:
    enabled: true
    name: kafka
    mountPath: "/var/data/kafka"
    readOnly: true
  injectAsEnvVars
    enabled: false
```
