### ISSUE TITLE
Support for CrunchyData Postgres Operator integration missing when user is specified

### ISSUE THREAD

**Issue by bennesp** [redhat-developer/service-binding-operator#1167]
### What is the environment (Minikube, Openshift)?
It happens on many different environments. Specifically I'm using minikube, eks, and rancher desktop.

### What is the SBO version used?
v1.0.1

### What are the steps to reproduce this issue?
Create a CrunchyData PostgresCluster, a Pod and binds them like the following:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-cluster
spec:
  users:
    - name: user1 # <----- NOTICE THIS
      databases:
        - database1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "1Gi"
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: sb-example
spec:
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgres-cluster
  application:
    name: test-sb-postgres
    group: apps
    version: v1
    resource: pods
---
apiVersion: v1
kind: Pod
metadata:
  name: test-sb-postgres
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container
```

### What is the expected behaviour?
The Pod has the data to connect to the database

### What is the actual behaviour?
The ServiceBinding fails with:

```yaml
status:
  conditions:
    - lastTransitionTime: '2022-06-13T17:01:32Z'
      message: secrets "postgres-cluster-pguser-postgres-cluster" not found
      reason: ProcessingError
      status: 'False'
      type: Ready
    - lastTransitionTime: '2022-06-13T17:01:32Z'
      message: secrets "postgres-cluster-pguser-postgres-cluster" not found
      reason: ErrorReadingBinding
      status: 'False'
      type: CollectionReady
```

Notice that it is searching for `postgres-cluster-pguser-postgres-cluster` and **not** for `postgres-cluster-pguser-user1` like it should.

I suppose that adding the support in #1043 with:
```
"service.binding": "path={.metadata.name}-pguser-{.metadata.name},objectType=Secret",
```
was slightly incorrect, because the part after `-pguser-` should match with the username and not with the `.metadata.name`

### Service Binding Operator Logs
```jsonl
{"level":"info","ts":1655140022.2553518,"logger":"controllers.ServiceBinding","msg":"Reconciling","serviceBinding":"default/sb-example"}
{"level":"info","ts":1655140022.3518617,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"default/sb-example","retry":true,"error":"secrets \"postgres-cluster-pguser-postgres-cluster\" not found"}
{"level":"error","ts":1655140022.3520422,"logger":"controller.servicebinding","msg":"Reconciler error","reconciler group":"binding.operators.coreos.com","reconciler kind":"ServiceBinding","name":"sb-example","namespace":"default","error":"secrets \"postgres-cluster-pguser-postgres-cluster\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
```

**Comment by baijum** [comment]
> was slightly incorrect, because the part after `-pguser-` should match with the username and not with the `.metadata.name`

What happens if there is more than one user in the array?

**Comment by bennesp** [comment]
More than one user results into having more than one secret.
More than one database results into ignoring all but the first database.

For example, testing with these resources:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-cluster
  annotations:
    service.binding: "path={.metadata.name}-pguser-{.spec.users[0].name},objectType=Secret"
spec:
  users:
    - name: user1
      databases:
        - database1
        - database2
    - name: user2
      databases:
        - database3
        - database4
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "1Gi"
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: sb-example
spec:
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgres-cluster
  application:
    name: test-sb-postgres
    group: apps
    version: v1
    resource: pods
---
apiVersion: v1
kind: Pod
metadata:
  name: test-sb-postgres
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container
```

results into having two secrets: `postgres-cluster-pguser-user1` and `postgres-cluster-pguser-user2`.

Those secrets have `dbname: "database1"` and `dbname: "database3"`
