### ISSUE TITLE
Discussion: Filter out fields from Service, Route resources for binding 

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#182]
This is a discussion thread to determine list of fields to extract from `Service` or `Route` yaml
for binding where binding annotations aren't available in OLM/CRD.

Related to https://jira.coreos.com/browse/APPSVC-115

Below are the sample yamls of `Service` and `Route` for reference.

**1. Service yaml**

```
spec:
  clusterIP: 172.30.131.201
  externalTrafficPolicy: Cluster
  ports:
    - name: web
      nodePort: 32595
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: nodejs-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
_Fields for binding_ 

- [x] spec.clusterIP
- [ ] spec.ports.name
- [ ] spec.ports.port
- [ ] spec.ports.targetPort
- [x] spec.ports.nodePort

**2. Route yaml**
```
spec:
  host: nodejs-example-myproject.192.168.99.102.nip.io
  to:
    kind: Service
    name: nodejs-example
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-25T07:08:37Z'
          status: 'True'
          type: Admitted
      host: nodejs-example-myproject.192.168.99.102.nip.io
      routerName: router
      wildcardPolicy: None
```

__Fields for Binding__
- [x] spec.host
