### ISSUE TITLE
Double base64 encoding for customEnvVar retrieved from a secret

### ISSUE THREAD

**Issue by pdettori** [redhat-developer/service-binding-operator#264]
I am using the customEnvVar to retrieve some values from a secret that I want to inject into a DeploymentConfig with a specific name for the environment variables, as those are the names used in existing node.js code. My service binding request looks like:

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: srb
spec:
  applicationSelector:
    matchLabels:
      connects-to: translator
      environment: demo
    group: apps.openshift.io
    version: v1
    resource: deploymentconfigs
  backingServiceSelector:
    group: ibmcloud.ibm.com
    version: v1alpha1
    kind: Binding
    resourceRef: mytranslator-binding
  customEnvVar:
    - name: LANGUAGE_TRANSLATOR_URL
      value: '{{ index .status.secretName "url" }}'
    - name: LANGUAGE_TRANSLATOR_IAM_APIKEY
      value: '{{ index .status.secretName "apikey" }}'
```

Expected Result: 
`LANGUAGE_TRANSLATOR_URL` and `LANGUAGE_TRANSLATOR_IAM_APIKEY` are present in the `binding-request` secret and the value is base64 encoded, so that I can get the actual value with base64 decode

Actual Result:
`LANGUAGE_TRANSLATOR_URL` and `LANGUAGE_TRANSLATOR_IAM_APIKEY` are present in the `binding-request` secret  but they are base64 encoded twice, so doing base64 decode provides a base64 encoded string which needs to be base64 decoded to get the actual value. This does not work with the existing node.js code.
