### ISSUE TITLE
"Error calling index" when using customEnvVar

### ISSUE THREAD

**Issue by pdettori** [redhat-developer/service-binding-operator#272]
I am running the service binding operator from master (b0c9641574269f58b6126a406bace6a4b2c07afd on Dec 5) and using `make local` to run. When I try to run the example in `examples/nodejs_postgresql` with the following service binding request:

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  applicationSelector:
    matchLabels:
      connects-to: postgres
      environment: demo
    group: apps.openshift.io
    version: v1
    resource: deploymentconfigs
  backingServiceSelector:
    group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    resourceRef: db-demo
  customEnvVar:
    - name: DB_USER
      value: '{{ index .status.dbConfigMap "db.username" }}'  
```

I get the following error:

```
{"level":"error","ts":1575664614.742795,"logger":"reconciler.bind","msg":"On saving secret data..","Request.Namespace":"service-binding-demo","Request.Name":"binding-request","ServiceBindingRequest.Name":"binding-request","error":"template: set:1:3: executing \"set\" at <index .status.dbConfigMap \"db.username\">: error calling index: index of untyped nil","stacktrace": ...
```
