### ISSUE TITLE
Feedback: supporting JSONPath syntax for customEnvVar in ServiceBindingRequests

### ISSUE THREAD

**Issue by navidsh** [redhat-developer/service-binding-operator#352]
Since `kubectl`/`oc` supports both JSONPath template and Go template, some k8s users might be more familiar with good old JSONPath :) over the Go template. Until more operators start adopting Service Binding Operator's descriptor/annotations, users need to rely on `customEnvVar` to bridge the gap.

An example for extracting broadcast address from Strimzi's Kafka CR:
```yaml
...
status:
  listeners:
    - addresses:
        - host: my-cluster-kafka-bootstrap.coffeeshop.svc
          port: 9092
      type: plain
```

`ServiceBindingRequest` to get the address using Go templates:
```yaml
  customEnvVar:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: |-
        {{- range .status.listeners -}}
          {{- if and (eq .type "plain") (gt (len .addresses) 0) -}}
            {{- with (index .addresses 0) -}}
              {{ .host }}:{{ .port }}
            {{- end -}}
          {{- end -}}
        {{- end -}}
```

Equivalent JSONPath template:
```yaml
  customEnvVar:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {range .status.listeners[?(@.type=="plain")].addresses[0]}{@.host}:{@.port}{end}
```

**Comment by sbose78** [comment]
Thanks for proposing this. This did come up intially during our initial design sessions. 

However, did you happen to check if an equivalent go template expression was possible?

**Comment by ianpartridge** [comment]
I guess you mean whether an equivalent JSONPath expression is possible?

The individual components can be fished out with:

```
$.status.listeners[?(@.type=='plain')].addresses[0].host
```
and
```
$.status.listeners[?(@.type=='plain')].addresses[0].port
```

**Comment by sbose78** [comment]
Ah yes, my bad. I wanted to write jsonpath. Thanks @ianpartridge .

**Comment by navidsh** [comment]
Thanks @ianpartridge.

Go Template:
```yaml
  customEnvVar:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: |-
        {{- range .status.listeners -}}
          {{- if and (eq .type "plain") (gt (len .addresses) 0) -}}
            {{- with (index .addresses 0) -}}
              {{ .host }}:{{ .port }}
            {{- end -}}
          {{- end -}}
        {{- end -}}
```

Equivalent(ish) Good old JSONPath =):
```yaml
  customEnvVar:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {range .status.listeners[?(@.type=="plain")].addresses[0]}{@.host}:{@.port}{end}
```

**Comment by navidsh** [comment]
@sbose78 as a side question, do you think it is possible to extract the `host:port` in the following example only by adding annotation/`x-descriptors` to the operator?

```yaml
status:
  listeners:
    - addresses:
        - host: my-cluster-kafka-bootstrap.coffeeshop.svc
          port: 9092
      type: plain
...
```

**Comment by sbose78** [comment]
I think the fact the _slice_ types may make it tricky @navidsh . @baijum @isutton Thoughts on what's the best way to express it as an annotation or an olm descriptor ?

**Comment by navidsh** [comment]
@baijum @isutton what do you guys think about using annotation/descriptors to get binding info from slice types?

Example:
```yaml
status:
  listeners:
    - addresses:
        - host: my-cluster-kafka-bootstrap.coffeeshop.svc
          port: 9092
      type: plain
...
```

**Comment by isutton** [comment]
What if we sprinkle some JSONPath in there?

```yaml
annotations:
  "binding/bootstrapServers": >
    {range .status.listeners[?(@.type=="plain")].addresses[0]}{@.host}:{@.port}{end}
```

This enables the interpretation of the manifest itself by different consumers, allowing the 
operator to be free of any details regarding a manifest schema, just treating the object
as a bag of structured data to apply the related JSONPath selectors.
