### ISSUE TITLE
Error: original object doesn't have a 'spec' field

### ISSUE THREAD

**Issue by pdettori** [redhat-developer/service-binding-operator#358]
I have installed the Service Binding Operator from OperatorHub, on OpenShift 4.3.0 on AWS (Installer-managed infrastructure)

These are the steps:
- Installed Service Binding Operator 0.0.24-214 from OperatorHub.
- Used defaults for install:
  - All namespaces on the cluster (default)
  - Update Channel: alpha
  - Approval Strategy: Automatic

Operator installation with OLM completes with `install strategy completed with no errors`, but then looking at the logs for the  service-binding-operator pod there are thousands of log entries like the following:

```
{"level":"error","ts":1583285272.1391072,"logger":"sbrcontroller.buildGVKPredicate","msg":"","GVK":"/v1, Kind=ConfigMap","error":"original object doesn't have a 'spec' field","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/redhat-developer/service-binding-operator/pkg/log.(*Log).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/pkg/log/log.go:35\ngithub.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.updateFunc.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/sbrcontroller.go:103\nsigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:79\nsigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:118\nk8s.io/client-go/tools/cache.(*processorListener).run.func1.1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:605\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:284\nk8s.io/client-go/tools/cache.(*processorListener).run.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nk8s.io/client-go/tools/cache.(*processorListener).run\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71"}
```

**Comment by sbose78** [comment]
Thanks!

**Comment by pdettori** [comment]
Just as additional piece of info, things are better if I install the operator in one namespace rather than  cluster-wide. This time the errors are about missing RBAC rules for Tekton.
```
E0304 20:40:18.729918       1 reflector.go:123] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *unstructured.Unstructured: tektoninstallations.toolchain.openshift.dev is forbidden: User "system:serviceaccount:service-binding-demo:service-binding-operator" cannot list resource "tektoninstallations" in API group "toolchain.openshift.dev" at the cluster scope
```

**Comment by pdettori** [comment]
To make things work in single namespace mode, I had to manually add the following cluster role and binding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-binding-operator-crb
rules:
- apiGroups:
  - tektoninstallations.toolchain.openshift.dev
  - config.operator.tekton.dev
  - cheinstallations.toolchain.openshift.dev
  - toolchain.openshift.dev
  - operator.tekton.dev
  resources:
  - '*'
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-binding-operator-binding
subjects:
- kind: ServiceAccount
  name: service-binding-operator
  namespace: service-binding-demo
roleRef:
  kind: ClusterRole
  name: service-binding-operator-crb
  apiGroup: rbac.authorization.k8s.io
```

**Comment by pdettori** [comment]
found another RBAC issue after creating the SBR, to make it work I had to add another rule for CRD access cluster-wide:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-binding-operator-crb
rules:
- apiGroups:
  - tektoninstallations.toolchain.openshift.dev
  - config.operator.tekton.dev
  - cheinstallations.toolchain.openshift.dev
  - toolchain.openshift.dev
  - operator.tekton.dev
  resources:
  - '*'
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-binding-operator-binding
subjects:
- kind: ServiceAccount
  name: service-binding-operator
  namespace: service-binding-demo
roleRef:
  kind: ClusterRole
  name: service-binding-operator-crb
  apiGroup: rbac.authorization.k8s.io
```

**Comment by sbose78** [comment]
Something doesn't look right - these should not be needed :)

```
rules:
- apiGroups:
  - tektoninstallations.toolchain.openshift.dev
  - config.operator.tekton.dev
  - cheinstallations.toolchain.openshift.dev
  - toolchain.openshift.dev
```

> found another RBAC issue after creating the SBR, to make it work I had to add another rule for CRD

I'm curious how it works today without this, wondering if OLM is doing some magic?

**Comment by pdettori** [comment]
It might be some issue with the way permissions are defined in https://github.com/operator-framework/community-operators/blob/master/community-operators/service-binding-operator/0.0.24-214/service-binding-operator.v0.0.24-214.clusterserviceversion.yaml ... have you had a chance to try to install from OperatorHub ?

**Comment by sbose78** [comment]
I've actually installed it multiple times and used it successfully too over the past few weeks 🤔

**Comment by Avni-Sharma** [comment]
I feel it is an OLM issue because if we see the status of the pod then the conditions are in a `success` phase 
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-05T05:14:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-05T05:14:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-05T05:14:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-05T05:14:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://bf36dba2f8585ce64adda6e5cea4ae7c026d2506d4ece2a630e75e843d364fdf
    image: quay.io/redhat-developer/app-binding-operator:794c252
    imageID: quay.io/redhat-developer/app-binding-operator@sha256:ff311c930ffe77b0e521533c37856b0643864b442028789a71241620188ee800
    lastState: {}
    name: service-binding-operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-03-05T05:14:56Z"
  hostIP: 10.0.147.49
  phase: Running
  podIP: 10.131.0.15
  podIPs:
  - ip: 10.131.0.15
  qosClass: BestEffort
  startTime: "2020-03-05T05:14:38Z"
```
