### ISSUE TITLE
Annotation/descriptors to get binding info from slice types

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#361]
https://github.com/redhat-developer/service-binding-operator/issues/352
 
feature request from @navidsh :

"What do you guys think about using annotation/descriptors to get binding info from slice types?

Example:
```yaml
status:
  listeners:
    - addresses:
        - host: my-cluster-kafka-bootstrap.coffeeshop.svc
          port: 9092
      type: plain
...
```
