### ISSUE TITLE
Annotations specifying more than one level of nesting is broken

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#372]
The scenario where an annotation specifies more than one level of nesting is broken.
x.y works, x.y.z doesn't work.

If the following annotation is used
```    
servicebindingoperator.redhat.io/spec.port.targetPort: 'binding:env:attribute'
```

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: example
  namespace: sbose
spec:
  host: example-sbose.apps.gitops2.devcluster.openshift.com
  path: /
  to:
    kind: Service
    name: example
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None

status:
      .....
      wildcardPolicy: None
      routerCanonicalHostname: apps.gitops2.devcluster.openshift.com

```

The value in the secret looks like this :

![image](https://user-images.githubusercontent.com/545280/76247051-42a27600-6215-11ea-8bfa-3fe7fa06673f.png)

Surprisngly,
If I added a customEnvVar {{ .spec.port.targetPort }} **after** adding the annotation, the right value shows up.
