### ISSUE TITLE
Generic binding: SBR needs to be cleaned up if applicationSelector is removed

### ISSUE THREAD

**Issue by navidsh** [redhat-developer/service-binding-operator#384]
Once `applicationSelector` is removed from a `ServiceBindingRequest`, the operator should update the CR to:

1. remove the `finalizer`
1. update `status.applications`

 ``` yaml
...
metadata:
  finalizers:
    - finalizer.servicebindingrequest.openshift.io
...
status:
  applications:
    - group: apps
      kind: Deployment
      name: barista-kafka
      version: v1
...
```

Also, the binding status is incorrect which causes operator to keep reconciling. There's already an issue open for this: https://github.com/redhat-developer/service-binding-operator/issues/381.
