### ISSUE TITLE
Support multiple backing services in customEnvVar / dataMapping

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#396]
JIRA story https://issues.redhat.com/browse/APPSVC-481

Extracted out https://github.com/redhat-developer/service-binding-operator/issues/356#issuecomment-596108001

```
backingServiceSelectors:
    - group: postgres.dev
      kind: Service
      resourceRef: user-db
      version: v1beta1
      id: X
    - group: postgres.dev
      kind: Credentials
      resourceRef: admin-creds
      version: v1beta1
      id: Y
customEnvVar:
    - name: CONNECTION_URL
       value: {{  X.status.username }} / {{ Y.status.url }}
```
