### ISSUE TITLE
As developer, I want to inject secret to my custom resource instance which has special path to container

### ISSUE THREAD

**Issue by ZhuangYuZY** [redhat-developer/service-binding-operator#400]
Edit by Shoubhik / Internal jira story:
https://issues.redhat.com/browse/APPSVC-276

--------------

The CRD has container which want to auto inject backing service instance secret as env variable. But the container jsonpath is not as "spec.template.spec.containers", the example of path is "spec.example.containers".

Do we have configuration in application selector section to indicate jsonpath where to inject secret ? If not, I think we need to support it. What do you think ? Thank you.

```
applicationSelector:
    resourceRef: helloworld
    group: abc.cloud
    version: v1
    resource: example
    inject_path: spec.example.containers
```

**Comment by sbose78** [comment]
Hey :)

I've been trying to model custom paths here
https://github.com/redhat-developer/service-binding-operator/pull/353

Could you please take a look?

**Comment by ZhuangYuZY** [comment]
Thank you. It is what we want.

**Comment by qibobo** [comment]
Hi @sbose78,
I picked the change #353 and deployed it. And did the following test.

1. Create a sample CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
    shortNames:
    - ac
```
2. Create a CR:
```
apiVersion: "stable.example.com/v1"
kind: AppConfig
metadata:
  name: demo-appconfig
spec:
  uri: "some uri"
  Command: "some command"
  image: my-image

```
3. Create a SBR:

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request-sample
spec:
  envVarPrefix: qiye111
  applicationSelector:
    resourceRef: demo-appconfig
    group: stable.example.com
    version: v1
    resource: appconfigs 
    bindingPath:
      customSecretPath: spec.uri
  backingServiceSelectors:
    - group: ibmcloud.ibm.com
      version: v1alpha1
      kind: Binding
      resourceRef: thetranslator2
      id: zzz
      envVarPrefix: qiye
  customEnvVar:
    - name: VCAP_SERVICES
      value: '{"language-translator":[{"credentials":{{to_json .zzz.status.secretName}},"name":"thetranslator2","plan":"standard"}]}'
    - name: TRANSLATOR_NAME
      value: "thetranslator2"
```

4. And then I get the CR and found the spec.uri is changed from its previous value "some uri" to the SBR(secret) name. Seems just a value replacement. Is it the expected behavior?

```
kubectl get ac demo-appconfig -o yaml
apiVersion: stable.example.com/v1
kind: AppConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"stable.example.com/v1","kind":"AppConfig","metadata":{"annotations":{},"name":"demo-appconfig","namespace":"default"},"spec":{"Command":"some command","image":"my-image","uri":"some uri"}}
  creationTimestamp: "2020-04-09T09:21:15Z"
  generation: 2
  name: demo-appconfig
  namespace: default
  resourceVersion: "19983"
  selfLink: /apis/stable.example.com/v1/namespaces/default/appconfigs/demo-appconfig
  uid: 47684eaa-d842-4c3f-be41-42511b2aec94
spec:
  Command: some command
  image: my-image
  uri: binding-request-sample

```

**Comment by sbose78** [comment]
Yes, similar to containers' envFrom secret ref.
Are you looking for a different behaviour?

**Comment by qibobo** [comment]
@sbose78 
We expect the `envFrom secret ref `behavior, but seems current is only a value replacement?

**Comment by sbose78** [comment]
Yes, that's right

**Comment by ZhuangYuZY** [comment]
Here is our scenario, which bind a service to a custom resouce.

CR which want to bind a service:
```
apiVersion: example.com/v1alpha1
kind: jobdef
metadata:
  name: jobsample
spec:
  containers:
  - name: jobsamplecontainer
    image: docker.io/example/jobsampleimage:latest
```

This is binding request:
```
spec:
  applicationSelector:
    resourceRef: jobsample
    group: example.com
    version: v1alpha1
    resource: jobdef
    bindingPath:
      podSpecPath:
        containers: spec.containers
```

There is expect result:
```
apiVersion: example.com/v1alpha1
kind: jobdef
metadata:
  name: jobsample
spec:
  containers:
  - name: jobsamplecontainer
    image: docker.io/example/jobsampleimage:latest
    - env:
       envFrom:
       - secretRef:
           name: jobsample-binding
```
