### ISSUE TITLE
Binding applied to a knative service without altering the explicit defined revision name is not allowed

### ISSUE THREAD

**Issue by int8dev** [redhat-developer/service-binding-operator#418]
If an exsiting ksvc has explicit revision name defined in `spec.template.metadata.name`, simply update the revision template without removing or altering the revision name will be rejected by knative validation webhook. See the error below.
```
"level":"error","ts":1586248488.1855843,"logger":"reconciler","msg":"On binding application.","Request.Namespace":"e884b530-8834","Request.Name":"binding-request-language-translator-kn","ServiceBindingRequest.Name":"binding-request-language-translator-kn","error":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: Saw the following changes without a name change (-old +new): spec.template.metadata.name
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].EnvFrom:
	-: \"[]\"
	+: \"[{Prefix: ConfigMapRef:nil SecretRef:&SecretEnvSource{LocalObjectReference:LocalObjectReference{Name:binding-request-language-translator-kn,},Optional:nil,}}]\"
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Env:
	-: \"[]\"
	+: \"[{Name:ServiceBindingOperatorChangeTriggerEnvVar Value:2020-04-07T08:34:48Z ValueFrom:nil}]\"
```

This should be a knative specific issue. I don't know whether it is accpetable to alter another field other than `containersPath` and `volumesPath` for service-binding-operator.

**Comment by sbose78** [comment]
Could you show me the Knative object - and show me the update you are attempting?

**Comment by int8dev** [comment]
If the knative service object is configured with a explicit revision name `demo-rev-1` as following, if we want to update the pod template in `.spec.template.spec` to inject the environment configurations, we must also change the revision name or just delete it to create a new revision. Otherwise it will be rejected as for a knative revision the pod template is immutable.
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo
spec:
  template:
    metadata:
      name: demo-rev-1
    spec: <omitted>
```

**Comment by ZhuangYuZY** [comment]
@int8dev As we talked, please help to give detail steps to reproduce the issue, and knative service yaml for both success and failure for comparing. It will help to everyone understand the situation happens on knative service. 
Also options of solution to fix the issue. We can discuss here together. Thank you.

**Comment by int8dev** [comment]
If we have a knative service defined with a explicit revision name `helloworld-go-rev1` as following
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
        name: helloworld-go-rev1
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"
```
If we want to inject or modify the container spec,  we must also change the name `helloworld-go-rev1` or just delete it. We can simulate by a kubectl command to just modify the existing environment by ` kubectl patch ksvc helloworld-go --type='json' -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0/value", "value":"Go Sample v2"}]'`

The knative webhook will reject the request with following error.
 ```
Error from server (BadRequest): admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Saw the following changes without a name change (-old +new): spec.template.metadata.name
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Env[0].Value:
	-: "Go Sample v1"
	+: "Go Sample v2"
```
I think we have two options to address this issue.
1) Just delete the revision name `helloworld-go-rev1` in the service object before applying binding. knative is obliged to generate a new revision name and avoid naming collision.
2) Append a suffix to generate a meaningful name based on the existing revision name. Let's say `helloworld-go-rev1-binding` for the example above. But this requires service binding operator to generate a unique name for each reconciling if template updating is needed.
