### ISSUE TITLE
tags for services

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#423]
I was thinking about the idea of allowing tags to be added to each of the backing services being requested in a `ServiceBinding` CR.   

Such data could then be exposed in the [SERVICE_BINDINGS](https://github.com/application-stacks/service-binding-specification#injecting-data) env var, helping the consumer locate the services they want.   This is equivalent to buildpack's `VCAP_SERVICES`, which has a set of tags per service instance.

**Comment by sbose78** [comment]
Could you share an example of what a tag would look like?

**Comment by arthurdm** [comment]
yup, here it is, using our favourite Kafka example :) 

```
  services:
    - group: kafka.strimzi.io
      kind: KafkaUser
      resourceRef: my-producer
      version: v1beta1
      id:  KAFKA_USER
      tags: kafka
    - group: kafka.strimzi.io
      kind: Kafka
      resourceRef: my-cluster
      version: v1beta1
      id:  KAFKA_CLUSTER
      tags: kafka, cluster1, events
```
