### ISSUE TITLE
Binding request fails with "application ResourceRef or MatchLabel not found" in spite of seemingly correct values

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#467]
Initially I tried to follow [this example ](https://github.com/redhat-developer/service-binding-operator/tree/179c2fb40bb274eeacace087320b00154a6d0e48/examples/nodejs_etcd_operator) to create a nodejs application that binds to etcd cluster. However, it failed with `application ResourceRef or MatchLabel not found` error.

Later, I was advised to use node code [from this repo](https://github.com/pmacik/nodejs-rest-http-crud).

### Steps followed
1. Using the OpenShift Developer Console, I created an application based on [nodejs-rest-http-crud](https://github.com/pmacik/nodejs-rest-http-crud).
2. Created an EtcdCluster using below configuration:
    ```yaml
    apiVersion: etcd.database.coreos.com/v1beta2
    kind: EtcdCluster
    metadata:
      name: example
    spec:
      size: 3
      version: 3.2.13
    ```

3. Used following yaml to create a service binding:
    ```yaml
   apiVersion: apps.openshift.io/v1alpha1
   kind: ServiceBindingRequest
   metadata:
     name: binding-request
     namespace: sbo
   spec:
     applicationSelector:
       group: apps
       version: v1
       resource: deployments
       resourceref: nodejs-rest-http-crud
     backingServiceSelector:
       group: etcd.database.coreos.com
       kind: EtcdCluster
       version: v1beta2
       resourceRef: example
     mountPathPrefix: ""
     customEnvVar: []
     detectBindingResources: true
    ```

### Actual result
Binding didn't get created for the requested service and application. Below is the output of `oc get sbr/binding-request -o yaml`
```yaml
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  creationTimestamp: "2020-05-14T07:21:27Z"
  generation: 1
  name: binding-request
  namespace: sbo
  resourceVersion: "370777"
  selfLink: /apis/apps.openshift.io/v1alpha1/namespaces/sbo/servicebindingrequests/binding-request
  uid: 59a8d33b-d535-4ff5-85e9-057d913a26eb
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceref: nodejs-rest-http-crud
    version: v1
  backingServiceSelector:
    group: etcd.database.coreos.com
    kind: EtcdCluster
    resourceRef: example
    version: v1beta2
  customEnvVar: []
  detectBindingResources: true
  mountPathPrefix: ""
status:
  conditions:
  - lastHeartbeatTime: "2020-05-14T08:16:46Z"
    lastTransitionTime: "2020-05-14T07:21:27Z"
    message: application ResourceRef or MatchLabel not found
    reason: BindingFail
    status: "False"
    type: Ready
  secret: binding-request

```

### Expected result
Binding to have successfully created.

**Comment by DhritiShikhar** [comment]
@dharmit There is a typo in `spec.applicationSelector.resourceref`
It's supposed to be `resourceRef:` with a capital R.

Can you try again with this change and let me know?

**Comment by dharmit** [comment]
This makes me feel really stupid. SBR gets created. 

Should the nodejs app now be able to store stuff? I still see `DB: NA` at the top of the page. And clicking save opens a box but nothing gets saved. :confused:

**Comment by DhritiShikhar** [comment]
Looking into it

**Comment by Avni-Sharma** [comment]
@dharmit can you check if the resourceRef is mentioned as `nodejs-rest-http-crud` or `nodejs-rest-http-crud-git` in topology?

**Comment by dharmit** [comment]
I tried but couldn't find `resourceRef` in the Topology view. So I checked `oc get deployments/nodejs-rest-http-crud -o yaml` and couldn't find `nodejs-rest-http-crud-git` anywhere. I do see a label `app.kubernetes.io/part-of: nodejs-rest-http-crud-app`.

Anyhow, I tried changing the `resourceRef` to all the three values that I mentioned above. But the `DB: NA` thing stays as-is.

**Comment by sbose78** [comment]
@dharmit That app isn't written in a way that it can 'understand' etcd :)  
However, to validate if binding has really happened, could you verify if the podSpec has the binding secret injected in the Deployment?

**Comment by dharmit** [comment]
> @dharmit That app isn't written in a way that it can 'understand' etcd :)

:disappointed: 

Is it possible to have such an example in the docs? The [ToDo app](https://github.com/akashshinde/node-todo) is pretty close. It fails to come up when created through Dev Console. But through `odo push`, I can spin it up just fine. However, the moment I create an sbr to connect it with an etcd cluster, something goes wrong.

It rightly creates a new pod after successful creation of sbr but fails to get started. `npm install` and `node server.js` commands don't work. Probably something we need to fix on odo side so that it restarts well. But it does have the `ETCD*` env vars in the pod.

> However, to validate if binding has really happened, could you verify if the podSpec has the binding secret injected in the Deployment?

Yes.
```yaml
spec:
  containers:
  - env:
    - name: ServiceBindingOperatorChangeTriggerEnvVar
      value: "2020-05-15T05:24:56Z"
    envFrom:
    - secretRef:
        name: binding-request
```

**Comment by Avni-Sharma** [comment]
@dharmit what does the `Status` show when you create the SBR. Does it show TRUE/FALSE

**Comment by dharmit** [comment]
> @dharmit what does the `Status` show when you create the SBR. Does it show TRUE/FALSE

It shows "True". 
```yaml
status:
  applications:
  - group: apps
    kind: Deployment
    name: nodejs-rest-http-crud
    version: v1
  conditions:
  - lastHeartbeatTime: "2020-05-19T04:22:00Z"
    lastTransitionTime: "2020-05-15T05:24:56Z"
    status: "True"
    type: Ready
  secret: binding-request
```
My original concern has been addressed. So I'll close this issue. Thanks for your help @DhritiShikhar @Avni-Sharma & @sbose78. :+1:
