### ISSUE TITLE
Unable to delete a service binding request if underlying application and/or service are deleted beforehand

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#535]
### What did I do? / Steps to reproduce
1. Created an application based on [this repo](https://github.com/akashshinde/node-todo) using OpenShift DevConsole.
2. Created an EtcdCluster service from its Operator.
3. Created a link between 1 & 2 using below yaml:
    ```yaml
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      name: binding-request
      namespace: myproject
    spec:
      applicationSelector:
        group: apps
        version: v1
        resource: deployments
        resourceRef: node-todo
      backingServiceSelector:
        group: etcd.database.coreos.com
        kind: EtcdCluster
        version: v1beta2
        resourceRef: example
      mountPathPrefix: ""
      customEnvVar: []
      detectBindingResources: true
    ```
4. Deleted either of the OpenShift objects created in 1 & 2.

### Actual behaviour
Unable to delete the service binding request created in step 3 above. The `oc delete` command seems to hang indefinitely.

### Expected behaviour
I'm not 100% sure. Should `oc delete` have worked? Or should the user be cautious to not delete either of the application or service before deleting SBR?
