### ISSUE TITLE
Unable to delete a service binding request in spite of setting "ownerReferences"

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#542]
### Steps to reproduce

1. Create an application based on [this repo](https://github.com/akashshinde/node-todo) using the "Topology" view of DevConsole.
2. Create an EtcdCluster from the Operator, again using "Topology"
3. Get the uid of the node application deployed in Step 1 - `oc get deployment/node-todo -o template="{{.metadata.uid}}"`.
4. Create an SBR with uid from previous step as `ownerReferences` like below:
    ```yaml
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      name: binding-request
      namespace: myproject
      ownerReferences:
      - apiVersion: apps/v1
        kind: Deployment
        name: node-todo 
        uid: 9075567a-a948-419a-ac28-639f4ca8a2b0
    spec:
      applicationSelector:
        group: apps
        version: v1
        resource: deployments
        resourceRef: node-todo
      backingServiceSelector:
        group: etcd.database.coreos.com
        kind: EtcdCluster
        version: v1beta2
        resourceRef: example
      mountPathPrefix: ""
      customEnvVar: []
      detectBindingResources: true
    ```
5. Delete the `node-todo` deployment using `oc delete deployment/node-todo`.

### Actual behaviour
SBR created using above steps doesn't get deleted in spite of setting `ownerReferences`.

### Expected behaviour
SBR should get deleted

### Note

* If I delete the application using "Topology" view, SBR does get deleted.
* Being able to automatically delete an SBR is important for `odo` because as a part of `odo link`, we are creating an SBR with `ownerReferences` info added (this is not available in `odo`'s master branch; it's on a feature branch on my fork). Upon doing `odo delete`, `odo` deletes the deployment and all the k8s objects that have the deployment set in their `ownerReferences` but SBR doesn't get deleted.
