### ISSUE TITLE
Decode data from source Secrets when detecting binding resources

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#553]
When detecting binding resources, data originating from a source Secret should be decoded before being stored in the target binding Secret. Currently, source Secret data is double encoded in the target binding Secret when generated as a result of detectBindingResources.

**Comment by sbose78** [comment]
That would make it pretty unusable I assume? 

Seems like a bug to me, @redhat-developer/service-binding could you take a look?

**Comment by baijum** [comment]
I tried to reproduce this issue with the following configuration, but I don't see the issue:
```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backends.stable.example.com
  annotations:
    servicebindingoperator.redhat.io/spec.secret: 'binding:env:object:secret:password'
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: backends
    singular: backend
    kind: Backend
    shortNames:
      - bk
---
apiVersion: "stable.example.com/v1"
kind: Backend
metadata:
  name: backend-demo
spec:
  secret: example-secret
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: hello-world
          image: yusufkaratoprak/kubernetes-gosample:latest
          ports:
            - containerPort: 8090
---
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
spec:
  envVarPrefix: qiye111
  applicationSelector:
    resourceRef: demo-deployment
    group: apps
    version: v1
    resource: deployments
  backingServiceSelectors:
    - group: stable.example.com
      version: v1
      kind: Backend
      resourceRef: backend-demo
      id: zzz
      envVarPrefix: qiye
```

This is the output from both secret objects:
```
$ kubectl get secret example-secret  -o jsonpath='{.data.password}'
MWYyZDFlMmU2N2Rm
$ kubectl get secret binding-request  -o jsonpath='{.data.QIYE111_QIYE_SECRET_PASSWORD}'
MWYyZDFlMmU2N2Rm
```

@ron1 Let me know if I missed something.
