### ISSUE TITLE
Significant memory leaks in SBO

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#605]
![Screenshot from 2020-08-10 16-31-48](https://user-images.githubusercontent.com/18097007/89907272-164ab580-dc0a-11ea-928b-df11ca92f8a5.png)

Reported by @bbrowning 
"Every peak of that blue took down an entire Node of the openshift cluster
In my case, as soon as the operator starts up it starts eating up memory."

Slack channel convo link https://coreos.slack.com/archives/CHK22LM6Y/p1597084375063000

**Comment by bbrowning** [comment]
It turns out the only reason these peaks are so spaced out is that when the memory leak takes down the Node running the SBO operator pod, another SBO operator pod gets spun up but fails to every acquire the leader lease until I got manually reboot the original failed Node. Once I do that, the memory usage immediately starts ramping up again.

So, the valley between those peaks is only representative of how often I manually reboot a Node.

**Comment by bbrowning** [comment]
Here's the memory usage of the service binding operator pod in my cluster for the last 2 hours:

![SBO memory usage](https://user-images.githubusercontent.com/56071/89918216-c0edb480-dbc7-11ea-9989-82812642b769.png)

**Comment by pmacik** [comment]
I wasn’t able to reproduce it with the current codebase, but I still have a few theories to check. Anyway, the version 0.3.0 for which this is targeted is a technology preview, for which a non-obvious and non-immediate memory leak is tolerable. I’m lowering a priority of the issue and moving the target version post 0.3.0 release (so that it is resolved in GA).

**Comment by pedjak** [comment]
@bbrowning are you still able to reproduce the issue with 0.3.0 version?

**Comment by bbrowning** [comment]
I have not reinstalled Service Binding Operator on a long-running cluster because it was causing the entire cluster to become unstable because of this leak. Unfortunately I don't plan to install it on that cluster again until / unless this is confirmed fixed.

**Comment by pedjak** [comment]
@bbrowning can you give us a bit more details on the load running on the cluster, so that we can create a similar one and hopefully reproduce the issue?

**Comment by isutton** [comment]
I've been slowly experimenting with it, and have a couple of notes to share.

Without any service binding load whatsoever, there's a difference between the configuration used in acceptance tests and production--more specifically the `WATCH_NAMESPACE` environment variable.

With `WATCH_NAMESPACE` set, the system doesn't seem to do anything out of ordinary.

With an empty `WATCH_NAMESPACE` variable, the system starts to behave differently than the previous case; I've observed two things sort of in parallel.

After the operator has started, multiple ConfigMap update events have been observed; some named `*-lock` seem to be used by several subsystems. Compare one of those ConfigMap resources over time:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"crc-tnpk6-master-0_f008bddf-74bd-4f5a-bfb3-dc8e1877ede5","leaseDurationSeconds":15,"acquireTime":"2020-11-23T13:36:59Z","renewTime":"2020-11-26T10:57:42Z","leaderTransitions":10}'
  creationTimestamp: "2020-11-13T11:25:45Z"
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"crc-tnpk6-master-0_f008bddf-74bd-4f5a-bfb3-dc8e1877ede5","leaseDurationSeconds":15,"acquireTime":"2020-11-23T13:36:59Z","renewTime":"2020-11-26T10:58:35Z","leaderTransitions":10}'
  creationTimestamp: "2020-11-13T11:25:45Z"
```
