### ISSUE TITLE
Docs: Add sample for java-openliberty & CrunchyData Postgresql Operator

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/service-binding-operator#611]
I am working on developing an end-to end jpa  sample/starter app for the java-openliberty odo stack and need to link it to the CrunchyData Postgresql Operator using odo link and the Service Binding Operator pattern. I have gotten through quite abit of it but am hitting a wall wrt the SBO and the intermediate secret that is generated.

To get this working, I have had to add certain annotations to the postgre CR YAML and I have modified the SBR yaml that was created by odo link to correctly configure the backingServiceSelectors block to gather up the pertinent backing service data into an intermediate secret... that info being the dbhost/port and the user/password

the backendServiceSelectors block in the SBR YAML, after I update it correctly,  looks like this:

```
backingServiceSelectors:
    - group: crunchydata.com
      kind: Pgcluster
      namespace: pgdata
      resourceRef: mydb
      version: v1
    - group: ''
      kind: Secret
      namespace: pgdata
      resourceRef: mydb-testuser-secret
      version: v1
```
The first group entry gets the dbhost/port from crunchy, and the 2nd group entry is supposed to get the user/password and those items should be then gathered up in the intermediate secret that gets created.

While I am getting a secret created, I am only getting the data associated with the 1st group entry (dbhost/port)
I was understanding that the second block was the way to obtain the user/password...but doesn't seem to result in the user/password data being put into the created secret.

After discussing with @isutton I added the following annotation to my db user secret (created for me by the CrunchyData operator):

```servicebindingoperator.redhat.io/data: binding:env:attribute```

And with that in place, the intermediate secret was generated with the username and password data included in it.

**Comment by sbose78** [comment]
> end-to end jpa sample/starter app for the java-openliberty

I would like to have you work featured in https://github.com/redhat-developer/service-binding-operator#example-scenarios . Would you be up for providing the details of the scenario you are trying out?  With that, you or someone could make a PR to add an example scenario ?

We would need:

* The App you are deploying.
* The DB operator you are installing. 
* The CR that was created to instance the db instance
* The ServiceBindingRequest object.

The advantage would be that, we'll eventually add the scenario into our e2e testing suite ( or we can show you how to if!), that way you/we know we aren't breaking it that scenario.

**Comment by ajm01** [comment]
Hi @sbose78 - Sure I would be happy to do that!

It looks like there is a scenario there for a Postgre Operator Managed DB, but would you be thinking that the scenario you propose I add would incorporate the odo link work from end to end?

**Comment by sbose78** [comment]
You could talk about "odo link", I'm okay either way!

Even though there's a PostgreSQL DB sample, yours deserves mention because of the use of the crunchybase PostgreSQL operator.

**Comment by ajm01** [comment]
OK, sounds good - makes sense.

**Comment by sbose78** [comment]
I fixed up your annotations a bit for the secret.

```
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    servicebindingoperator.redhat.io/spec.usersecretname-PASSWORD: 'binding:env:object:secret'
    servicebindingoperator.redhat.io/spec.usersecretname-USERNAME: 'binding:env:object:secret'
```

... and after doing so, the following worked well - multiple backing service selectors were not needed.

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: nodejs-ex-d-postgres-operator-d
  namespace: sbose
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceRef: nodejs-ex
    version: v1
  backingServiceSelector:
    group: crunchydata.com
    kind: Pgcluster
    resourceRef: example
    version: v1
status:
  applications:
    - group: apps
      kind: Deployment
      name: nodejs-ex
      version: v1
  conditions:
    - lastHeartbeatTime: '2020-08-13T18:46:53Z'
      lastTransitionTime: '2020-08-13T18:41:02Z'
      status: 'True'
      type: CollectionReady
    - lastHeartbeatTime: '2020-08-13T18:46:54Z'
      lastTransitionTime: '2020-08-13T18:41:03Z'
      status: 'True'
      type: InjectionReady
  secret: nodejs-ex-d-postgres-operator-d
```
