### ISSUE TITLE
Using service binding with cockroachdb

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#632]
**Created a sample instance of cockroachdb**

```
apiVersion: charts.helm.k8s.io/v1alpha1
kind: Cockroachdb
metadata:
  annotations:
    servicebindingoperator.redhat.io/spec.conf.port: 'binding:env:attribute' <------- Service binding attribute
  name: example
  namespace: pgo
spec:
  networkPolicy:
    enabled: false
    ingress:
      grpc: []
      http: []
  conf:
    port: 26257
    logtostderr: INFO
    attrs: []
    cache: 25%
    locality: ''
    disable-cluster-name-verification: false
    http-port: 8080
    single-node: false
    max-sql-memory: 25%
    max-disk-temp-storage: 0
    join: []
    max-offset: 500ms
    sql-audit-dir: ''
    cluster-name: ''
  init:
    affinity: {}
    annotations: {}
    labels:
      app.kubernetes.io/component: init
    nodeSelector: {}
    resources: {}
    tolerations: []
  service:
    discovery:
      annotations: {}
      labels:
        app.kubernetes.io/component: cockroachdb
    ports:
      grpc:
        external:
          name: grpc
          port: 26257 
        internal:
          name: grpc-internal
          port: 26257
      http:
        name: http
        port: 8080 <---------- Question ? How do I retrieve this ?
    public:
      annotations: {}
      labels:
        app.kubernetes.io/component: cockroachdb
      type: ClusterIP
  statefulset:
    nodeSelector: {}
    annotations: {}
    resources: {}
    budget:
      maxUnavailable: 1
    nodeAffinity: {}
    secretMounts: []
    env: []
    podAffinity: {}
    podAntiAffinity:
      type: soft
      weight: 100
    podManagementPolicy: Parallel
    replicas: 3
    tolerations: []
    updateStrategy:
      type: RollingUpdate
    args: []
    labels:
      app.kubernetes.io/component: cockroachdb
  tls:
    certs:
      clientRootSecret: cockroachdb-root
      nodeSecret: cockroachdb-node
      provided: false
      tlsSecret: false
    enabled: false
    init:
      image:
        credentials: {}
        pullPolicy: IfNotPresent
        repository: cockroachdb/cockroach-k8s-request-cert
        tag: '0.4'
    serviceAccount:
      create: true
      name: ''
  image:
    credentials: {}
    pullPolicy: IfNotPresent
    repository: cockroachdb/cockroach
    tag: v19.2.5
  storage:
    hostPath: ''
    persistentVolume:
      annotations: {}
      enabled: true
      labels: {}
      size: 100Gi
      storageClass: ''
  clusterDomain: cluster.local
  labels: {}
status:
  conditions:
    - lastTransitionTime: '2020-08-21T20:43:29Z'
      status: 'True'
      type: Initialized
    - lastTransitionTime: '2020-08-21T20:43:33Z'
      message: >
        CockroachDB can be accessed via port 26257 at the

        following DNS name from within your cluster:


        example-cockroachdb-public.pgo.svc.cluster.local


        Because CockroachDB supports the PostgreSQL wire protocol, you can
        connect to

        the cluster using any available PostgreSQL client.


        For example, you can open up a SQL shell to the cluster by running:

            kubectl run -it --rm cockroach-client \
                --image=cockroachdb/cockroach \
                --restart=Never \
                --command -- \
                ./cockroach sql --insecure --host=example-cockroachdb-public.pgo

        From there, you can interact with the SQL shell as you would any other
        SQL

        shell, confident that any data you write will be safe and available even
        if

        parts of your cluster fail.


        Finally, to open up the CockroachDB admin UI, you can port-forward from
        your

        local machine into one of the instances in the cluster:

            kubectl port-forward example-cockroachdb-0 8080

        Then you can access the admin UI at http://localhost:8080/ in your web
        browser.


        For more information on using CockroachDB, please see the project's docs
        at:

        https://www.cockroachlabs.com/docs/
      reason: InstallSuccessful
      status: 'True'
      type: Deployed
```

**Created a Service Binding**

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: example-servicebindingrequest
  namespace: pgo
spec:
 backingServiceSelector:
    group: charts.helm.k8s.io
    kind: Cockroachdb
    resourceRef: example
    version: v1alpha1
  detectBindingResources: true
status:
  conditions:
    - lastHeartbeatTime: '2020-08-21T21:17:46Z'
      lastTransitionTime: '2020-08-21T20:53:22Z'
      status: 'True'
      type: CollectionReady
    - lastHeartbeatTime: '2020-08-21T21:17:46Z'
      lastTransitionTime: '2020-08-21T20:53:22Z'
      message: application selectors are empty
      reason: EmptyApplicationSelector
      status: 'False'
      type: InjectionReady
  secret: example-servicebindingrequest
```

**This is how the secret looks like**

```
kind: Secret
apiVersion: v1
metadata:
  name: example-servicebindingrequest
  namespace: pgo
  ownerReferences:
    - apiVersion: apps.openshift.io/v1alpha1
      kind: ServiceBindingRequest
      name: example-servicebindingrequest
      uid: 4f372878-6bcf-4226-9b5e-8d76ffc8b749
      controller: true
data:
  COCKROACHDB_CLUSTERIP: MTcyLjMwLjEwMS4zNA==
  COCKROACHDB_CONF_PORT: MjYyNTc=
type: Opaque
```
