### ISSUE TITLE
Using Service Binding with Anzo DB operator 

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#633]
Didn't find anything special to annotate, but `detectBindingResources` came very handy.

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: sbr-anzo
  namespace: sbose
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceRef: nodejs-rest-http-crud
    version: v1
  backingServiceSelector:
    group: anzograph.clusters.cambridgesemantics.com
    kind: AnzoGraph
    resourceRef: azg01
    version: v1
  detectBindingResources: true
status:
  conditions:
    - lastHeartbeatTime: '2020-08-21T22:37:31Z'
      lastTransitionTime: '2020-08-21T22:35:03Z'
      status: 'True'
      type: CollectionReady
    - lastHeartbeatTime: '2020-08-21T22:37:32Z'
      lastTransitionTime: '2020-08-21T22:35:03Z'
      message: application not found
      reason: ApplicationNotFound
      status: 'False'
      type: InjectionReady
  secret: sbr-anzo
```

```
kind: Secret
apiVersion: v1
metadata:
  name: sbr-anzo
  namespace: sbose
  ownerReferences:
    - apiVersion: apps.openshift.io/v1alpha1
      kind: ServiceBindingRequest
      name: sbr-anzo
      uid: db37c8dd-dfc7-48cc-beaf-cb861921afed
      controller: true
data:
  ANZOGRAPH_GRPCQUERYUSER: WjNKd1kzRjFaWEo1
  ANZOGRAPH_UIADMINPASSWORD: YjFNNWFsbzRkVlpp
  ANZOGRAPH_CLUSTER_NAME: YXpnMDE=
  ANZOGRAPH_UIQUERYUSERPASSWORD: UkROMlF6VkJWMWd6T1VsV1ZWZFRVREk9
  ANZOGRAPH_NAMESPACE: c2Jvc2U=
  ANZOGRAPH_GRPCADMINUSER: WjNKd1kyRmtiV2x1
  ANZOGRAPH_UIQUERYUSER: Y1hWbGNuaz0=
  ANZOGRAPH_APP: YW56b2dyYXBo
  ANZOGRAPH_CLUSTERIP: MTcyLjMwLjY0Ljgy
  ANZOGRAPH_UIADMINUSER: WVdSdGFXND0=
  ANZOGRAPH_REPLICA_COUNT: Mg==
  ANZOGRAPH_ANZOGRAPH.PROFILE.FILE: c3RhbmRhbG9uZQ==
  ANZOGRAPH_DEPLOY_FRONTEND: ZmFsc2U=
  ANZOGRAPH_GRPCADMINPASSWORD: VVVoamFWZDJjVnBVWVRKT09UVlNlRkpVV2c9PQ==
  ANZOGRAPH_GRPCQUERYUSERPASSWORD: UlZWellVUTJTRVZrZWpCVWFHSllabEUyY0E9PQ==
type: Opaque
```
