### ISSUE TITLE
Troubles getting binding:env:object:secret annotation to work

### ISSUE THREAD

**Issue by durera** [redhat-developer/service-binding-operator#646]
CRD currently looks something like this (experimenting with a minimal CR that holds mongodb connection properties that I'm trying to use servicebindingrequest to get into a simple demo app):

in namespace 1 we have the CR, and a secret:

The CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ...
  annotations:
    servicebindingoperator.redhat.io/status.configDb: binding:env:attribute
    servicebindingoperator.redhat.io/status.credentials-password: binding:env:object:secret
    servicebindingoperator.redhat.io/status.credentials-username: binding:env:object:secret
    servicebindingoperator.redhat.io/status.hosts: binding:env:attribute
  ...
```

The status object of the CR looks like this:
```
status:
  conditions:
  - ansibleResult:
      changed: 2
      completion: 2020-08-27T17:54:00.33111
      failures: 0
      ok: 8
      skipped: 0
    lastTransitionTime: 2020-08-27T17:53:36Z
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
  configDb: admin
  credentials: secretname
  hosts:
  - host: <removed>
    port: <removed>
  - host: <removed>
    port: <removed>
```

Where `secretname` is a secret that contains the name of a secret that hold username/password in it's data.  

Over in namespace 2, all of the `binding:env:attribute` stuff "just works" -- the servicebindingrequest created and injected the data into my deployment using the intermediary secret:

```
apiVersion: v1
data:
  MONGODB_CONFIGDB: <removed>
  MONGODB_HOSTS_0_HOST: <removed>
  MONGODB_HOSTS_0_PORT: <removed>
  MONGODB_HOSTS_1_HOST: <removed>
  MONGODB_HOSTS_1_PORT: <removed>
kind: Secret
...
```

But I cannot for the life of me get the username and password pulled out of the referenced secret.  

The docs seem to indicate that the annotation should be `servicebindingoperator.redhat.io/status.credentials.password: binding:env:object:secret`, however looking at the postgres example the format used there has a "-" to seperate the resource and the property name, implying I should be using an annotation of `servicebindingoperator.redhat.io/status.credentials-password: binding:env:object:secret` (see: [PR](https://github.com/operator-backing-service-samples/postgresql-operator/commit/2d1821c1d4ebb43940e44e9f6f75af48aadd66e4). 

Neither works for me so far, and I can't see any errors in the service binding operator logs either, and the status of the binding request indicates it's happy enough.

```
  - lastHeartbeatTime: 2020-08-27T18:34:30Z
    lastTransitionTime: 2020-08-27T18:34:14Z
    status: "True"
    type: CollectionReady
  - lastHeartbeatTime: 2020-08-27T18:34:30Z
    lastTransitionTime: 2020-08-27T18:34:14Z
    status: "True"
    type: InjectionReady
```

Kind of at a loss where to go from here to be honest :)
