### ISSUE TITLE
service-binding-operator panics if there is a configMapRef in envFrom

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#648]
To reproduce this issue.
Create an app with a configMapRef inside its envFrom, then after creating a SBR, the service-binding-operator panics.

```
  envFrom:
      - configMapRef:
          name: seed-defaults
```
The operator log:

```
{"level":"info","ts":1598593249.9040349,"logger":"reconciler","msg":"Saving data on intermediary secret...","Request.Namespace":"default","Request.Name":"binding-request-sample","ServiceBindingRequest.Name":"binding-request-sample"}
E0828 05:40:49.930262       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1653 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14e0540, 0x23fbce0)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14e0540, 0x23fbce0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).appendEnvFrom(0xc00023a8c0, 0xc000117540, 0x1, 0x1, 0xc000420e00, 0x16, 0xc0002fac00, 0xc000bdcfc8, 0x118a195)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:366 +0x47
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).updateContainer(0xc00023a8c0, 0x14d5de0, 0xc00082cae0, 0x0, 0x0, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:414 +0xbf
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).updateContainers(0xc00023a8c0, 0xc000540170, 0x1, 0x1, 0x1, 0x0, 0x0, 0xffffffffffffffff, 0xc000bdd180)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:309 +0x1e3
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).updateSpecContainers(0xc00023a8c0, 0xc0001aa888, 0xc000420e00, 0x16, 0xc0001aa880)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:248 +0x8f
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).update(0xc00023a8c0, 0xc0001170c0, 0x0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:540 +0x3db
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*binder).bind(0xc00023a8c0, 0xc000bdd620, 0x0, 0x169f89b, 0x4, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/binder.go:634 +0x71
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*serviceBinder).bind(0xc0002fcc30, 0x16d5b5c, 0x30, 0x0, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/servicebinder.go:321 +0x3f1
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.(*reconciler).Reconcile(0xc0005dab40, 0xc0006df179, 0x7, 0xc0008ff1e0, 0x16, 0x1, 0xbfca4418695d38f0, 0xc0008ec6c0, 0xc0005eb338)
	/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/reconciler.go:263 +0xd5f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00067e540, 0x1538740, 0xc000707240, 0x0)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00067e540, 0xc0007a8b00)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00067e540)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000425970)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000425970, 0x3b9aca00, 0x0, 0x1743e01, 0xc0005b7380)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000425970, 0x3b9aca00, 0xc0005b7380)
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1384c67]
```
The whole steps to reproduce this issue:
```
cat <<EOF | kubectl -n default apply -f -
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
    shortNames:
    - ac
EOF

cat <<EOF | kubectl -n default apply -f -
apiVersion: "stable.example.com/v1"
kind: AppConfig
metadata:
  name: demo-appconfig
spec:
  uri: "some uri"
  Command: "some command"
  image: my-image
  spec:
    containers:
    - name: hello-world
      image: yusufkaratoprak/kubernetes-gosample:latest
      envFrom:
      - configMapRef:
          name: seed-defaults
      ports:
      - containerPort: 8090

EOF

cat <<EOF | kubectl -n default apply -f -
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request-sample
spec:
  envVarPrefix: qiye111
  applicationSelector:
    resourceRef: demo-appconfig
    group: stable.example.com
    version: v1
    resource: appconfigs 
    bindingPath:
      podSpecPath:
        containers: spec.spec.containers
  backingServiceSelectors:
    - group: ibmcloud.ibm.com
      version: v1alpha1
      kind: Binding
      resourceRef: thetranslator5
      id: zzz
      envVarPrefix: qiye
EOF
```
