### ISSUE TITLE
How to parse a json object in binding secret

### ISSUE THREAD

**Issue by s0uravd3** [redhat-developer/service-binding-operator#717]
Hi team,
Im trying to create a Service Binding Request using the `redis` bound secret from IBM Cloud. The secret is one json object with `connection` details inside it. Its not as straightforward as the examples where there are separate key-value pairs for each attribute (user, password, host, etc).

Is there a way to parse a `connection` key's json value (similar to jq) and then map the same to a customEnvVar?

Something like : 
```
  customEnvVar:
     - name: REDIS_USER
       value: '{{ index .status.secretName "connection" .jq.rediss.username }}'
     - name: REDIS_PASSWORD
       value: '{{ index .status.secretName "connection" .jq.rediss.password }}'
```
