### ISSUE TITLE
Controller doesn't reconcile when BackingService CR got deleted and recreated

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#723]
steps to reproduce this issue:

I use [bindings.ibmcloud](https://github.com/IBM/cloud-operators/blob/master/config/crd/bases/ibmcloud.ibm.com_bindings.yaml) as the backing service. And I have added the annotations as below to the bindings CRD.

```
    service.binding/secretName: path={.status.secretName},objectType=Secret
    service.binding/serviceName: path={.spec.serviceName}
```

1 create the BackingServiceCR:

```
cat <<EOF | kubectl apply -f -
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
    name: thetranslator
spec:
    serviceName: thetranslator
EOF
```

2 create the knative service as the app

```
cat <<EOF | kubectl apply -f -
apiVersion: serving.knative.dev/v1
kind: Service 
metadata:
  name: knative-vcap
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/qibobo/go4autoscaler:latest
          ports:
          - containerPort: 8080
EOF
```

3 create the SBR
```
cat <<EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-request-knative
spec:
  application:
    group: serving.knative.dev
    version: v1
    resource: services
    name: knative-vcap
  services:
  - group: ibmcloud.ibm.com
    version: v1alpha1
    kind: Binding
    name: thetranslator
    envVarPrefix: serviceprefix
    id: thetranslator
  customEnvVar:
    - name: VCAP_SERVICES
      value: '{"language-translator":[{"credentials":{{json .thetranslator.status.secretName}},"name":"thetranslator","plan":"standard"}]}'
    - name: TRANSLATOR_NAME
      value: "thetranslator"
    - name: URL
      value: '{{.thetranslator.status.secretName.url}}'
EOF
```

Now there are 2 secrets named thetranslator(generated by BackingService) and binding-request-knative(generated by SBO) and the content of the 2 secrets are equal.

5 delete and re-create the BackingServiceCR
```
kubectl delete binding.ibmcloud thetranslator
cat <<EOF | kubectl apply -f -
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
    name: thetranslator
spec:
    serviceName: thetranslator
EOF
```

Now the secret thetranslator has changed to new content but the SBO does not do anything, and the secret binding-request-knative's content is still old , which is already stale.
