### ISSUE TITLE
Binding using annotation with elementType=sliceOfStrings fails with `unsupported type` error

### ISSUE THREAD

**Issue by pmacik** [redhat-developer/service-binding-operator#728]
# Steps to reproduce
## Scenario 1:  `sliceOfStrings` from array
Given a CRD is annotated with service binding annotation using the `sliceOfStrings` element type like in the following snippet:

```yaml
...
metadata:
   annotations:
      service.binding/tags: path={.spec.tags},elementType=sliceOfStrings
```

and the respective CR contains the following spec:

```yaml
...
kind: Backend
...
spec:
   tags:
      - knowledge
      - is
      - power
```
when a service binding is created to bind the service CR to an application I'd expect that the application would be enriched with the following env variables by the binding:

```shell
BACKEND_TAGS_0="knowledge"
BACKEND_TAGS_1="is"
BACKEND_TAGS_2="power"
```

However the following error is being thrown instead:

```
2020-10-14T13:28:35.086+0200	ERROR	controller-runtime.controller	Reconciler error	{"controller": "servicebinding-controller", "request": "service-binding-demo/binding-request", "error": "unsupported type"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88

```
## Scenario 2: `sliceOfStrings` from values in slice of maps by key
Given a CRD is annotated with service binding annotation using the `sliceOfStrings` element type like in the following snippet:

```yaml
...
metadata:
   annotations:
      service.binding/url: path={.spec.connections},elementType=sliceOfStrings,sourceValue=url
```

and the respective CR contains the following spec:

```yaml
...
kind: Backend
...
spec:
    connections:
      - type: primary
        url: primary.example.com
      - type: secondary
        url: secondary.example.com
      - type: '404'
        url: black-hole.example.com
```
when a service binding is created to bind the service CR to an application I'd expect that the application would be enriched with the following env variables by the binding:

```bash
BACKEND_URL_0="primary.example.com"
BACKEND_URL_1="secondary.example.com"
BACKEND_URL_2="black-hole.example.com"
```

However the following error is being thrown instead:

```
2020-10-15T12:47:40.743+0200	ERROR	controller-runtime.controller	Reconciler error	{"controller": "servicebinding-controller", "request": "service-binding-demo/binding-request", "error": "unsupported type"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/home/pmacik/.go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```
## Acceptance Tests to verify this are covered by https://github.com/redhat-developer/service-binding-operator/pull/729
