### ISSUE TITLE
SBO should re-attempt to update deployment with correct secret name in case of modification by external factor

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#744]
When secret name is updated in the deployment by a user (external factor), 

SBO should re-attempt to update the deployment with correct secret name.

Refer - https://youtu.be/F8r-pDBq7UA

**Comment by Avni-Sharma** [comment]
I tried to run it against v0.3.0 red hat operator

When I updated the secret ref from binding-request to something else like binding. The reconcile is triggered and we get the binding-request back again. But yes the old secret ref and the binding-request secret ref both exist, which is okay, things wont break as we are getting the binding-request back. example I get this after following the steps from the video

```
        envFrom:
        - secretRef:
            name: bindin
        - secretRef:
            name: binding-request
```

So I had changed the secret ref name as a user from binding-requst to bindin. The controller retriggered and added binding-request back.
