### ISSUE TITLE
IBM Cloud Operator mapping does not work

### ISSUE THREAD

**Issue by haf-tech** [redhat-developer/service-binding-operator#816]
IBM Cloud Operator 1.0.0
Red Hat Service Binding Operator 0.4.0

Trying to create the secrets using the IBM Cloud Operator service binding. Generally the secret will be created, but the mapping does not work. The generate contains the entire keys or the specified keys, but with key names starting with `BINDING_`

IBM Cloud Operator definition:
```
apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
  name: language-translator-demo
  namespace: ico-test  
spec:
  plan: Alias
  serviceClass: language-translator
  externalName: "Language Translator-o6"
---
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
    name: language-translator-demo
    namespace: ico-test
    # Annotation to support Red Hat Service Binding Operator
    annotations:
      service.binding/url: path={.status.secretName},objectType=Secret,sourceValue=url
      service.binding/apikey: path={.status.secretName},objectType=Secret,sourceValue=apikey
spec:
    serviceName: language-translator-demo
```

RH Service Binding definition
```

apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: svc-binding-lang-translate-nodejs
  namespace: ico-test
spec:
  services:
  - group: ibmcloud.ibm.com
    version: v1
    kind: Binding
    name: language-translator-demo
    id: tr
  application:
    name: app-svc-binding-demo
    group: apps
    version: v1
    resource: deployments
  mappings:
     - name: SVC_LANGUAGE_TRANSLATOR_URL
       value: '{{ .tr.status.secretName.url }}'
     - name: SVC_LANGUAGE_TRANSLATOR_APIKEY
       value: '{{ .tr.status.secretName.apikey }}'
```

The generated secret
```
apiVersion: v1
data:
  BINDING_APIKEY: aFJ...
  BINDING_URL: aHR0...
kind: Secret
type: Opaque
```

I do not see how the mapping is really related to the secret creation and the keys in the generated secret still have `BINDING` as prefix.
Any idea?
