### ISSUE TITLE
Problem generating binding secret based on annotations

### ISSUE THREAD

**Issue by durera** [redhat-developer/service-binding-operator#824]
Version: 0.4.0 from OperatorHub (preview channel)

I'm switching over our PoC code from the old `ServiceBindingRequest` to the new `ServiceBinding` resource ... based on the doc here https://github.com/redhat-developer/service-binding-operator/blob/master/docs/SBO%20User%20Guide.md#use-the-attribute-statusdataconnectionurl-as-uri-in-the-binding-secret these are the new annotations I have added to our CRD:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    servicebinding.dev/api_ca_crt: path={.status.api.certs.ca}
    servicebinding.dev/api_tls_crt: path={.status.api.certs.tls}
    servicebinding.dev/api_url: path={.status.api.url}
  creationTimestamp: "2020-12-30T12:37:45Z"
```

This is a snippet of what I have in the CR:
```
status:
  api:
    certs:
      ca: |
        -----BEGIN CERTIFICATE-----
        xxx
        -----END CERTIFICATE-----
      tls: |
        -----BEGIN CERTIFICATE-----
        xxx
        -----END CERTIFICATE-----
    serviceName: sls
    url: https://sls.ibm-sls.svc/api
```

I'm expecting a BindingRequest like this to produce a secret named `sls-binding-request` containing three keys `LICENSESERVICE_API_URL`, `LICENSESERVICE_API_CA_CRT`, `LICENSESERVICE_API_TLS_CRT`:
```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: sls-binding-request
  namespace: mas-inst1
spec:
  services:
  - group: sls.ibm.com
    version: v1
    kind: LicenseService
    name: sls
    namespace: ibm-sls
```

However, I get an empty secret and in the operator I see the error `path should exist in both objects: [data]`:

```
{"level":"info","ts":1609346067.1339889,"logger":"reconciler","msg":"application selectors are empty","Request.Namespace":"mas-inst1","Request.Name":"sls-binding-request","ServiceBinding.Name":"sls-binding-request"}
{"level":"info","ts":1609346067.1363506,"logger":"reconciler","msg":"Reconciling ServiceBinding...","Request.Namespace":"mas-inst1","Request.Name":"sls-binding-request"}
{"level":"info","ts":1609346067.5424705,"logger":"reconciler","msg":"Binding applications with intermediary secret...","Request.Namespace":"mas-inst1","Request.Name":"sls-binding-request","ServiceBinding.Name":"sls-binding-request"}
{"level":"info","ts":1609346067.632203,"logger":"secret","msg":"Secret data is different; update secret","Namespace":"mas-inst1","Name":"sls-binding-request","Diff":"  map[string]interface{}(\n- \tnil,\n+ \t{},\n  )\n"}
Current APPLICATION IS :  <nil>
{"level":"info","ts":1609346067.8317063,"logger":"reconciler","msg":"application selectors are empty","Request.Namespace":"mas-inst1","Request.Name":"sls-binding-request","ServiceBinding.Name":"sls-binding-request"}
{"level":"error","ts":1609346228.582952,"logger":"sbrcontroller.buildGVKPredicate","msg":"error comparing object fields","GVK":"/v1, Kind=ConfigMap","error":"path should exist in both objects: [data]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/redhat-developer/service-binding-operator/pkg/log.(*Log).Error
  /tmp/github.com/redhat-developer/service-binding-operator/pkg/log/log.go:35
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding.updateFunc.func1
  /tmp/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding/sbrcontroller.go:130
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go:79
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:118
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292
k8s.io/client-go/tools/cache.(*processorListener).run.func1
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1
  /tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71"}
```

The latter error, then repeats on interval.

I know the operator is working in some sense, because if I add `detectBindingResources: true` to the BindingRequest then the secret is populated with the following, which represents various secrets/configmaps owned by the resource as expected.

```
data:
  LICENSESERVICE_CLUSTERIP: <snip>
  LICENSESERVICE_EMBEDDED_YAML: <snip>
  LICENSESERVICE_LICENSING_YAML: <snip>
  LICENSESERVICE_MONGO_YAML: <snip>
  LICENSESERVICE_TRUSTSTORE_P12: <snip>
  LICENSESERVICE_TRUSTSTORE_PASSWORD: <snip>
```

I can't work out what I need to do/where I went wrong to get the secret content populated based on my annotations, ie. this: 

```
data: 
  LICENSESERVICE_API_URL: xxx
  LICENSESERVICE_API_TLS_CRT: xxx
  LICENSESERVICE_API_CA_CRT: xxx
```
