### ISSUE TITLE
Support for keys containing a "."

### ISSUE THREAD

**Issue by durera** [redhat-developer/service-binding-operator#826]
How can one reference a key that contains a `.`, I have tried using `\.` to escape the dot as I would it I were writing a jsonpath statement, but no dice:

```yaml
annotations:
  service.binding/jks: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore.jks
  service.binding/p12: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore.p12
  service.binding/password: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore_password
```

```yaml
annotations:  
  service.binding/jks: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore\.jks
  service.binding/p12: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore\.p12
  service.binding/password: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore_password
``` 

The former I didn't expect to work, but both produce the same result: a secret containing only the password (which oddly ends up in a property named `TRUSTSTORE` rather than `TRUSTSTORE_PASSWORD`, perhaps I have misunderstood how the part after the `/` works, but I expected `service.binding/password` to result in `data,TRUSTSTORE_PASSWORD` rather than `data.TRUSTSTORE`:

```yaml
data:
  TRUSTSTORE: NlpBcW .. <snip>
```

The following works:

```yaml
service.binding/truststore: path={.status.truststore.secret},objectType=Secret
```

Producing:

```yaml
data:
  TRUSTSTORE_TRUSTSTORE_JKS: xxx
  TRUSTSTORE_TRUSTSTORE_P12: xxx
  TRUSTSTORE_TRUSTSTORE_PASSWORD: xxx
```

I can't seem to find any way to tell the operator "please don't apply a Type prefix", nor a way to instruct the operator to expand the secret directly onto the type'd prefix, as the following produces exactly the same result and I hoped might omit the middle `TRUSTSTORE_`: 

```yaml
service.binding: path={.status.truststore.secret},objectType=Secret
```

## Mistake in the Docs
Also, FYI the example in the doc is in error: https://github.com/redhat-developer/service-binding-operator/blob/master/docs/SBO%20User%20Guide.md#use-certificate-from-the-configmap-statusdatadbconfiguration-as-an-environment-variable

The example annotation given is the same as the previous use-case, and would pull in the entire secret:

```
"servicebinding.dev/certificate": "path={.status.data.dbConfiguration},objectType=ConfigMap"
```

This should be:
```
"service.binding/certificate": "path={.status.data.dbConfiguration},objectType=ConfigMap,sourceKey=certificate"
```

## Mappings
Finally, I tried to use a mapping to see if that was a way around this:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: "trust-binding"
  namespace: mas-inst1
spec:
  services:
  - group: trust-manager.ibm.com
    version: v1
    kind: Truststore
    name: inst1-truststore
    namespace: mas-inst1
    id: ts1
  
  mappings:
    name: foo
    value: '{{ .ts1.status.truststore.secret }}'
```

Not sure if I'm using that right, but nothing new appeared in the secret.  It's not clear to me how these play into the annotations, it appears these bypass any definition of what to share on the service end and allow the service making the binding request to have complete control over what to pluck out of the status of the CR, however I couldn't get it to work.  

The spec above should -- if I understand correctly -- pull the name of the secret from the status of the CR and add it to the fields in the secret managed by the service binding operator even though it's not defined as something to share in the annotations on the CRD:

**Comment by Avni-Sharma** [comment]
Hi @durera  For the mappings it should be a list of the (name,value) pair . Something like 
```
                mappings:
                   - name: foo
                     value: '{{ .ts1.status.truststore.secret }}'
```
Refer:
https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/customEnvVar.feature#L45

**Comment by Avni-Sharma** [comment]
For the `"servicebinding.dev/certificate": "path={.status.data.dbConfiguration},objectType=ConfigMap"` and `"service.binding/certificate": "path={.status.data.dbConfiguration},objectType=ConfigMap,sourceKey=certificate"` if the sourceKey is not mentioned explicitly, as mentioned in the latter case, then by default the key that is taken is whatever is mentioned after `/`

**Comment by Avni-Sharma** [comment]
At the moment, binding names declared through annotations or CSV descriptors are processed before injected into the application according to the following strategy:

- names are upper-cased
- service resource kind is upper-cased and prepended to the name
For example, if the service is of kind Database and the binding name is host, then the environment variable injected into the application is DATABASE_HOST.

The current approach is not flexible and makes it impossible for many applications to bind without changing them. We should open up a possibility to apply some other naming strategy, or none if needed, for example:

- none
- uppercasing ( service kind + binding name)
- naming template (fully customizable approach)

The intention is to incorporate the above-mentioned naming strategy. Maybe we can have a proposal PR under docs/proposals for the same for more feedback on this.. cc @akashshinde @sbose78

**Comment by Avni-Sharma** [comment]
There is also a workaround if you wish to omit the service kind as a prefix to names populated in the secret. You can give `namePrefix: ""`  Reference https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/injectBindingsAsFiles.feature#L258

**Comment by jasperchui** [comment]
====== Not related to this issue ======
Hi David, 

We are looking to start a community call for this project on Thursdays and wanted to reach out to see if you were interested in participating.  If you are could you send us your email to service-binding-support@redhat.com and we can include you in the invite? Thanks.

Jasper

**Comment by durera** [comment]
Yeah, I'd be interested in participating in that (sorry for delay, busy few weeks here) I've followed up on the e-mail address provided above :+1:

**Comment by CAIOFCP** [comment]
Hi there, was there a resolution for the main problem reported on this issue. What should be done when trying to use sourceKeys where the key name has `.` ?

**Comment by pedjak** [comment]
I believe that this issue is solved in the latest SBO release, can somebody confirm it? In essence, for an annotation like:

```
service.binding/jks: path={.status.truststore.secret},objectType=Secret,sourceKey=truststore.jks
```

and service CR with status:

```yaml
status:
  truststore:
    secret: mysecret
```

and secret:

```yaml
data:
   truststore.js: <content>
```

you are going to get binding `jks` with value `<content>`
