### ISSUE TITLE
Service binding is creating a secret with wrong key when sourceKey is mentioned in annotation

### ISSUE THREAD

**Issue by pratikjagrut** [redhat-developer/service-binding-operator#838]
I was trying to bind a backend service to an application using annotation in CRD
```
service.binding/certificate: path={.status.data.dbConfiguration},objectType=ConfigMap,sourceKey=certificate
```

This is CR:
```
apiVersion: stable.example.com/v1
kind: Backend
metadata:
    name: cmsa-1-service
spec:
    image: docker.io/postgres
    imageName: postgres
    dbName: db-demo
status:
    data:
        dbConfiguration: cmsa-1-configmap    # ConfigMap
```
This is CM:
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: cmsa-1-configmap
data:
    certificate: "certificate value"
```
This is sb cr:
```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
    name: cmsa-1
spec:
    services:
      - group: stable.example.com
        version: v1
        kind: Backend
        name: cmsa-1-service
    application:
        name: cmsa-1
        group: apps
        version: v1
        resource: deployments
```

Expected intermediate secret data:

```
BACKEND_CERTIFICATE: Y2VydGlmaWNhdGUgdmFsdWU=
```

Actual intermediate secret data:
```
BACKEND: Y2VydGlmaWNhdGUgdmFsdWU=
```

Acceptance test to reproduce: https://github.com/redhat-developer/service-binding-operator/pull/842
