### ISSUE TITLE
Service binding doesn't work with nested objects

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#858]
Hi
I have been using latest 0.4.0 version of operator from beta channel (preview was not allowing us to create binding using example projects)

I'm trying to build a very simple service that will provide SBO info.
My CRD has config defined as follows:
```yaml
    service.binding/bootstrapServer: 'path={.status.bootstrapServer.host}'
    service.binding/user: 'path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=clientID'
    service.binding/password: 'path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=clientSecret'
    service.binding/saslMechanism: 'path={.status.saslMechanism}'
    service.binding/securityProtocol: 'path={.status.securityProtocol}'
```

MY CR has this status values:
```
      boostrapServer
			host: test
	  message: Created
	  saslMechanism: PLAIN
	  securityProtocol: SSL
	  serviceAccountSecretName: testsecret
	  updated: '2021-02-04T15:32:53.047087Z'
```

When I go to the application I see only:
```
sh-4.2$ env | grep FIREPIG
FIREPIG_CONNECTION_SECURITYPROTOCOL=SSL
FIREPIG_CONNECTION_SASLMECHANISM=PLAIN
```
This is missing values like bootstrapServer. 
I looks like latest SBO version has some issues around fetching nested objects in spec.
There is no information about the issue. I also see pod terminating uncontrollably and putting some strain on the cluster. 

My binding
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
spec:
  application:
    group: apps
    name: nodejs-sample
    resource: deployments
    version: v1
  detectBindingResources: true
  services:
    - group:redhat.com
      kind: Connection
      name: test
      version: v1alpha1
```
