### ISSUE TITLE
Documentation for SBO status

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#859]
Hi 

I would like to know when SBO operator works properly based on the status. 
Is there any docs for those statuses?
```
conditions:
    - lastHeartbeatTime: '2021-02-04T16:15:06Z'
      lastTransitionTime: '2021-02-04T15:33:11Z'
      status: 'True'
      type: CollectionReady
```
