### ISSUE TITLE
Feedback: Provide more complex example w/TLS-based auth and User CRD

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#86]
Backing Service operators like https://operatorhub.io/operator/strimzi-kafka-operator and https://operatorhub.io/operator/mongodb-enterprise support TLS-based authentication (SCRAM-SHA over TLS, TLS mutual authentication, etc.) and support individual User CRs (kafka.strimzi.io/v1beta1 - KafkaUser, mongodb.com/v1 - MongoDBUser) that are distinct from the Backing Service CR.

When TLS-based authentication is in use, how are the ca.crt and optional tls.crt/tls.key integrated into the client app deployment? Is the secret hosting these resources mounted as a volume?

Also when a backing service separates User CRs from the Service CR, how are servicebindingrequest annotations on the CRs defined? It is likely connection-related parameters are included in the backing service CR and credential-related parameters are included in the user CR via a secret.

A proposed Service Binding mockup for one of these types of backing services would be helpful to fully understand the feature set.

**Comment by baijum** [comment]
We have a PR opened to add volume mount: #83

**Comment by sbose78** [comment]
Thank you @ron1 !

> When TLS-based authentication is in use, how are the ca.crt and optional tls.crt/tls.key integrated into the client app deployment? Is the secret hosting these resources mounted as a volume?

If the backing service operator controller _puts_ the certs in a secret and is annotated as `urn:alm:descriptor:servicebinding:volumemount:secret:ca.crt`, the binding controller could mount it:

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  applicationSelector:
    matchLabels:
      connects-to: postgres
      environment: demo
    resourceKind: DeploymentConfig
  backingServiceSelector:
    resourceKind: postgresql.baiju.dev
    resourceVersion: v1alpha1
    resourceRef: db-demo
  mountPathPrefix: “/var/certs”
```

Note, there's an option for a mount path prefix, which defaults to `/var/data`

```
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/var/certs"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: service-binding-secret
      items:
      - key: ca.crt
        path: ca.crt
```

( @pmacik , please add this to the scenario list. )
