### ISSUE TITLE
Service bindings causing infinite reconcile loops in operators

### ISSUE THREAD

**Issue by durera** [redhat-developer/service-binding-operator#866]
## Observed behaviour
SBO is updating the status field of the ServiceBinding constantly, even when nothing in the binding has changed.  

## Desired behaviour
The ServiceBinding resource should only be changed by the SBO operator when there is a meaningful change to the status of the binding that should be communicated.

## Result
For bindings deployed by operators, operator will be in an infinite reconcile loops, starting a reconcile as soon as the last one completes because this resource that it owns (the service binding) has been reported as "changed".

## More Info
e.g. today we have an operator, it deploys a service binding.  This service binding will have an ownerReference in it, and we take advantage of the built in capabilioty in k8s to have our operator run a reconcile cycle whenever any resource it owns changes so that we can action any changes as a result of that change across the entire application.  Every time SBO updates the status conditions to report a heartbeat, our operator is forced into a full reconcile loop.

We would only like to see the ServiceBinding resource being changed if there is something meaningful changed about the binding that would necessitate the application that established the binding taking some action.

`lastTransitionTime` is useful to us, if anythign changes we can pick it up, but `lastHeartbeatTime` is just causing the application to think "this binding changed" every time it is updated.

Would it be poissible to either change the default behaviour, or introduce an operator-friendly mode that could be toggled by a property in the ServiceBinding if a change to the default behaviour would be too disruptive to other usecases?

```
$ oc get servicebinding feb07-sls-binding -o yaml | yq .status
{
  "conditions": [
    {
      "lastHeartbeatTime": "2021-02-07T16:29:07Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "status": "True",
      "type": "CollectionReady"
    },
    {
      "lastHeartbeatTime": "2021-02-07T16:29:07Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "message": "application selectors are empty",
      "reason": "EmptyApplication",
      "status": "False",
      "type": "InjectionReady"
    },
    {
      "lastHeartbeatTime": "2021-02-07T16:29:07Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "status": "True",
      "type": "Ready"
    }
  ],
  "secret": "feb07-sls-binding"
}
```

```
$ oc get servicebinding feb07-sls-binding -o yaml | yq .status
{
  "conditions": [
    {
      "lastHeartbeatTime": "2021-02-07T16:30:09Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "status": "True",
      "type": "CollectionReady"
    },
    {
      "lastHeartbeatTime": "2021-02-07T16:30:09Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "message": "application selectors are empty",
      "reason": "EmptyApplication",
      "status": "False",
      "type": "InjectionReady"
    },
    {
      "lastHeartbeatTime": "2021-02-07T16:30:09Z",
      "lastTransitionTime": "2021-02-07T16:08:24Z",
      "status": "True",
      "type": "Ready"
    }
  ],
  "secret": "feb07-sls-binding"
}
```

**Comment by pedjak** [comment]
thanks for the excellent writeup. What should considered as significant change in order to update conditions? For example:
* Service `foo` is bound to application `bar`, conditions are set to reflect that
* Service `foo` got updated, the operator detects that, inject updated bindings into the app
* Should the operator change anything on conditions? It looks like it should not?

**Comment by durera** [comment]
Sorry for the delay, vacation and other work got in the way of picking this up ... we're running master in our clusters now and will get back to you in the coming days with any feedback :+1:

**Comment by sbose78** [comment]
Thank you,  @durera !

**Comment by durera** [comment]
I've noticed using the master build of SBO the naming for the binding secret has changed and is returned in the status field.

```
status:
  conditions:
  - lastTransitionTime: "2021-02-26T17:30:54Z"
    message: ""
    reason: BindingInjected
    status: "True"
    type: CollectionReady
  - lastTransitionTime: "2021-02-26T17:30:54Z"
    message: application selectors are empty
    reason: EmptyApplication
    status: "False"
    type: InjectionReady
  - lastTransitionTime: "2021-02-26T17:30:54Z"
    message: ""
    reason: EmptyApplication
    status: "True"
    type: Ready
  secret: djpfeb26-sls-binding-527a0bc2d50749a7b837bcd5630473fe2aeb3122
```

Is there a new configuration option that allows us to mirror behaviour similar to before e.g. define the desired secretName in the spec? 

```
spec:
apiVersion: "{{ apiVersions.servicebindings }}"
kind: ServiceBinding
metadata:
  name: "{{ secretPrefix }}sls-binding"
  namespace: "{{ coreNamespace }}"
spec:
  services:
    - group: sls.ibm.com
      kind: LicenseService
      name: "{{ sls.name }}"
      namespace: "{{ sls.namespace }}"
      version: v1
  secretName: "{{ secretPrefix }}sls-binding"
```

At the moment 99% of our code doesn't need to change whether SBO is used or not, adding ABO to the picture brings additional value to the user in keeping thigns in sync automatically, but if took SBO out of the picture everything still works, it's just the data doesn't flow between systems automatically now.  Most of the code only sees the intermediate secret (which to us, isn't intermediate, it's the end game for SBO), and there's no difference to the codebase who or how the secret was created, we would need updates throughout the code to do stuff like this now:

- check whether the SBO resource "xxxx" exists
- if it exists get the secret name from it's status, e.g. "xxxx-randomstring"
- use secret "xxxx", or secret "xxxx-randomstring" depending on the result of the above checks.
