### ISSUE TITLE
Direct Secret reference

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#872]
I'm trying to create a binding between Deployment and Secret as described in https://github.com/k8s-service-bindings/spec#direct-secret-reference

I have a secret with passwords for my database
```
▶ kubectl describe secrets my-mysql
Name:         my-mysql
Namespace:    tkral-test
Labels:       app.kubernetes.io/instance=my-mysql
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mysql
              helm.sh/chart=mysql-8.3.1
Annotations:  meta.helm.sh/release-name: my-mysql
              meta.helm.sh/release-namespace: tkral-test

Type:  Opaque

Data
====
mysql-password:       10 bytes
mysql-root-password:  10 bytes
```

I'm trying to reference this  `Secret` directly in `ServiceBinding` as described in https://github.com/k8s-service-bindings/spec#direct-secret-reference
```
▶ kubectl get servicebindings.operators.coreos.com mysql-binding  -o yaml
```
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: mysql-binding
  namespace: tkral-test
spec:
  application:
    group: apps
    name: python-mysql
    resource: deployments
    version: v1
  detectBindingResources: true
  services:
  - group: ""
    kind: Secret
    name: my-mysql
    version: v1
status:
  conditions:
  - lastHeartbeatTime: "2021-02-12T16:54:40Z"
    lastTransitionTime: "2021-02-12T16:52:34Z"
    status: "True"
    type: CollectionReady
  - lastHeartbeatTime: "2021-02-12T16:54:40Z"
    lastTransitionTime: "2021-02-12T16:52:34Z"
    status: "True"
    type: InjectionReady
  - lastHeartbeatTime: "2021-02-12T16:54:40Z"
    lastTransitionTime: "2021-02-12T16:52:34Z"
    status: "True"
    type: Ready
  secret: mysql-binding
```

But Secret that was created by `ServiceBinding` is empty
```
▶ kubectl describe secret mysql-binding
Name:         mysql-binding
Namespace:    tkral-test
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
```

I'm using Service Binding Operator v0.4.0
