### ISSUE TITLE
Feedback: Enhance ServiceBindingRequest to support simple secret transforms

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#88]
Often, the secret generated by the service-binding-operator based on the backing service CRD annotations requires transformation before it is usable by the client application. The Service Catalog ServiceBinding (https://svc-cat.io/docs/resources/#servicebinding) and the KubeDB AppBinding (https://github.com/kmodules/custom-resources/blob/711575c0b8a9fda8169c1035048558f5bb1fe91c/apis/appcatalog/v1alpha1/appbinding_types.go#L180) support simple JSON-based transforms. Consider enhancing the ServiceBindingRequest to support these as well.

Some example JSONPath SecretTransforms are available here: https://trello.com/c/UmdhbQd8/129-catalog310-better-credentials-remapping-w-jsonpath-templates. An extract of some examples are inlined below:

1) Add a new key like this:
```
secretTransform:
- addKey:
    key: "my-new-key"
    stringValue: "my-new-value"

or:

secretTransform:
- addKey:
    key: "my-new-key"
    value: base64-encoded-byte-array-value
```

2) Merge an existing Secret into the credentials Secret:
```
secretTransform:
- addKeysFrom:
    secretRef: 
      namespace: my-namespace
      name: my-other-secret
```
3) You can also create a new key by transforming existing keys (this uses a JSONPath template):
```
secretTransform:
- addKey:
    key: "my-new-key"
    jsonPathExpression: "key one is {.special-key-1}, key two is {.special-key-2}"
```
4) Remove an entry from credentials Secret:
```
secretTransform:
- removeKey:
    key: "special-key-1"
```
