### ISSUE TITLE
It is not possible to recreate binding (deleting binding will not allow it to be reapplied)

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#889]
I try to apply single service per binding approach but that fails.

```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: apache-kafka
  namespace: wtrocki-testing
spec:
  application:
    group: apps
    name: nodejs-sample
    resource: deployments
    version: v1
  bindAsFiles: true
  #namingStrategy: 'APACHE_KAFKA__{{ .name | upper }}_ENV'
  services:
    - group: rhoas.redhat.com
      version: v1alpha1
      kind: ManagedKafkaConnection
      name: kafka
```

Creating this binding twice will fail with 
```
conditions:
    - lastTransitionTime: '2021-03-02T14:58:04Z'
      message: ''
      reason: BindingInjected
      status: 'True'
      type: CollectionReady
    - lastTransitionTime: '2021-03-02T14:58:04Z'
      message: >-
        Deployment.apps "nodejs-sample" is invalid:
        spec.template.spec.containers[0].volumeMounts[1].name: Not found:
        "apache-kafka"
      reason: BindingFail
      status: 'False'
      type: InjectionReady
    - lastTransitionTime: '2021-03-02T14:58:04Z'
      message: ''
      reason: BindingFail
      status: 'False'
      type: Ready
```

This is not blocking me but logging as known issue
