### ISSUE TITLE
ServiceBindings for deployment configs using filesystem do not mount properly

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#940]
Deploy Kafka quickstart:
https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-quickstart

1. Create binding
```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: kafka-quickstart-dc-sharedkafka-akc
  namespace: wtrocki-final
spec:
  application:
    group: apps.openshift.io
    name: kafka-quickstart
    resource: deploymentconfigs
    version: v1
  bindAsFiles: true
  detectBindingResources: true
  services:
    - group: rhoas.redhat.com
      kind: KafkaConnection
      name: sharedkafka
      version: v1alpha1
```

Binding finishing with the proper status but binding doesn't appear in the pod.

When doing binding for node.js application that has deployment (instead of deployment config) all works fine
