### ISSUE TITLE
Improve Service Binding status error message

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#958]
## Problem 

The ServiceBinding status reports the error message "not found" without specifying what is not found - application or service.

```
status:
  conditions:
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: not found
    reason: ErrorReadingBinding
    status: "False"
    type: CollectionReady
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: not found
    reason: ProcessingError
    status: "False"
    type: Ready
```

## Expected behaviour

It would be good to have a more descriptive error message specifying `resource` and `namespace`. `namespace` should also be there because Service Binding Operator [would like to work across namespaces](https://github.com/redhat-developer/service-binding-operator/issues/938). 

Example:

```
status:
  conditions:
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: service `db-demo` not found in namespace `default`
    reason: ErrorReadingBinding
    status: "False"
    type: CollectionReady
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: service `db-demo` not found in namespace `default`
    reason: ProcessingError
    status: "False"
    type: Ready
```

AND

```
status:
  conditions:
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: application `nodejs-todo` not found in namespace `devtools`
    reason: ErrorReadingBinding
    status: "False"
    type: InjectionReady
  - lastTransitionTime: "2021-04-27T06:39:17Z"
    message: application `nodejs-todo` not found in namespace `devtools`
    reason: ProcessingError
    status: "False"
    type: Ready
```

**Comment by kadel** [comment]
> [<img alt="@pedjak" width="20" height="20" src="https://avatars.githubusercontent.com/u/132690?s=60&amp;v=4">](/pedjak) [pedjak](/pedjak) added the [ priority/low ](/redhat-developer/service-binding-operator/labels/priority%2Flow) label [20 hours ago](#event-5026735355)

Would it be possible to give this higher priority. This effects SBO usability. 
As a user if I don't better guidance what is wrong I won't be able to correct the issue and use SBO.

**Comment by baijum** [comment]
We have a good error message now.
```
status:
  conditions:
  - lastTransitionTime: "2022-08-08T03:10:28Z"
    message: no matches for kind "BackingService" in version "app.example.org/v1alpha1"
    reason: ErrorReadingServices
    status: "False"
    type: CollectionReady
  - lastTransitionTime: "2022-08-08T03:10:28Z"
    message: no matches for kind "BackingService" in version "app.example.org/v1alpha1"
    reason: ProcessingError
    status: "False"
    type: Ready
  observedGeneration: 1
```
