### ISSUE TITLE
Mapping with IBM Cloud Operator v1 not working anymore

### ISSUE THREAD

**Issue by haf-tech** [redhat-developer/service-binding-operator#961]
### What is the environment (Minikube, Openshift)?
OCP 4.5

### What is the SBO version used?
0.7.1

### What are the steps to reproduce this issue?
  1. IBM Cloud Operator, Service binding, with annotation etc, following the example defined here https://github.com/redhat-developer/service-binding-operator/blob/master/examples/nodejs_ibmcloud_operator/README.md
  

### What is the expected behaviour?
Secret created with defined field names, from mapping

### What is the actual behaviour?
Mapping does not understanding the definition

```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: svc-binding-lang-translate-nodejs
  namespace: ico-test
spec:
  # false: bind as env var
  bindAsFiles: false
  services:
  - group: ibmcloud.ibm.com
    version: v1
    kind: Binding
    name: language-translator-demo
    id: tr
  application:
    name: app-svc-binding-demo
    group: apps
    version: v1
    resource: deployments
  mappings:
     - name: SVC_LANGUAGE_TRANSLATOR_API_KEY
       value: '{{ .tr.status.secretName.apikey }}'
```

### Service Binding Operator Logs

```
{"level":"info","ts":1620934533.425429,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"ico-test/svc-binding-lang-translate-nodejs","retry":false,"error":"template: mappings:1:6: executing \"mappings\" at <.tr.status.secretName.apikey>: can't evaluate field apikey in type interface {}"}
```

### Additional Information (Screenshots, etc)

The configuration worked with version 0.4.0

**Comment by pedjak** [comment]
> value: '{{ .tr.status.secretName.apikey }}'

As a part of aligning with [the spec](https://github.com/servicebinding/spec), we dropped support for paths that go across resources. In order to restore the previous behavior you would need to perform following:

* add annotation `service.binding/apiKey: path={.status.secretName},objectType=Secret,sourceKey=apiKey` to your service or its CRD
* construct mappings as:
```yaml
mappings:
     - name: SVC_LANGUAGE_TRANSLATOR_API_KEY
       value: '{{ .apiKet }}'
```

Please reopen if you have any further questions.
