### ISSUE TITLE
Support for array element selection in jsonpath for paths in annotations

### ISSUE THREAD

**Issue by feloy** [redhat-developer/service-binding-operator#963]
### What is the environment (Minikube, Openshift)?

Minikube

### What is the SBO version used?

master

### What are the steps to reproduce this issue?

- Create a statefulset:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db1
  annotations:
    service.binding/address: path={.spec.serviceName}
    service.binding/postgre_user: path={.spec.template.spec.containers[0].env[?(@.name=="POSTGRESQL_USER")].value}
spec:
  selector:
    matchLabels:
      app: db1
  serviceName: db1
  replicas: 1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
      - name: db1
        image: centos/postgresql-96-centos7
        env:
        - name: POSTGRESQL_USER
          value: user1
        - name: POSTGRESQL_PASSWORD
          value: k33p5ecret
        - name: POSTGRESQL_DATABASE
          value: mydb
        ports:
        - containerPort: 5432
          name: pg
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: data
        emptyDir: {}
```
- Create a servicebinding:

```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding

metadata:
  name: binding-request
  namespace: prj1

spec:
  application:
    group: apps
    version: v1
    resource: deployments
    name: api

  services:
    - group: apps
      version: v1
      kind: StatefulSet
      name: db1
      namespace: prj1
```

### What is the expected behaviour?

- The operator should be able to find the value `user1` for the path `.spec.template.spec.containers[0].env[?(@.name=="POSTGRESQL_USER")].value` as the path is valid jsonpath

### What is the actual behaviour?

The annotations are ignored as the paths are not recognized as valid jsonpath

### Additional Information (Screenshots, etc)

Fix proposal at #964
