### ISSUE TITLE
`detectBindingResources` is binding to a wrong Service

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#966]
### What is the environment (Minikube, Openshift)?
minikube

### What is the SBO version used?
v0.7.1

#### 1. deployed sample deployment and operator and operand into the same namespace called `test`
  
<details>
 <summary>deployment.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: busybox
        name: busybox
```
</details>

<details>
 <summary>operator.yaml</summary>

```yaml

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: test
spec:
  targetNamespaces:
  - test
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-postgresql-operator-dev4devs-com
  namespace: test
spec:
  channel: alpha
  name: postgresql-operator-dev4devs-com
  source: operatorhubio-catalog
  sourceNamespace: olm
```
</details>

<details>
 <summary>operand.yaml</summary>

```yaml
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: postgresql
  namespace: test
spec:
  databaseName: example
  databasePassword: postgres
  databaseStorageRequest: 1Gi
  databaseUser: postgres
  image: centos/postgresql-96-centos7
  size: 1

```
</details>

#### 2. created SericeBinding with `detectBindingResources: true`
<details>
 <summary>binding.yaml</summary>

```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: busybox-postgresql
  namespace: test
spec:
  application:
    group: apps
    name: busybox
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
    - group: postgresql.dev4devs.com
      kind: Database
      name: postgresql
      namespace: test
      version: v1alpha1
```
</details>

In my namespace, there are two Services

```
▶ k get svc
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
postgresql                    ClusterIP   10.110.53.111   <none>        5432/TCP            14m
postgresql-operator-metrics   ClusterIP   10.99.217.236   <none>        8383/TCP,8686/TCP   14m
```

`postgresql-operator-metrics` Service  has operator (`Database.postgresql.dev4devs.com`) as `ownerReference`

```
▶ k get svc postgresql-operator-metrics -o jsonpath="{.metadata.ownerReferences}" | jq
[
  {
    "apiVersion": "apps/v1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "Deployment",
    "name": "postgresql-operator",
    "uid": "8c11676c-fb8d-4881-8f71-ddcba37581f2"
  }
]
```

`postgresql` Service has operand (`Database.postgresql.dev4devs.com`) as `ownerReference`
```
▶ k get svc postgresql -o jsonpath="{.metadata.ownerReferences}" | jq                 
[
  {
    "apiVersion": "postgresql.dev4devs.com/v1alpha1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "Database",
    "name": "postgresql",
    "uid": "43149969-d701-460a-8566-4337cbe4cc50"
  }
]
```

### What is the expected behaviour?
Deployment `busybox` has `DATABASE_CLUSTERIP` env variable containing IP address of the **`postgresql`** Service

### What is the actual behaviour?

Deployment `busybox` has `DATABASE_CLUSTERIP` env variable containing IP address of the **`postgresql-operator-metrics`** Service which is not tied to the `service` defined in `ServiceBinding` 

```
▶ k exec -it busybox-75fcb776bc-5m4hr -- env | grep CLUSTERIP                                         
DATABASE_CLUSTERIP=10.99.217.236
```

```
▶ k get svc
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
postgresql                    ClusterIP   10.110.53.111   <none>        5432/TCP            14m
postgresql-operator-metrics   ClusterIP   10.99.217.236   <none>        8383/TCP,8686/TCP   14m
```

### Service Binding Operator Logs

<details>
 <summary>logs</summary>

```
{"level":"info","ts":1621435172.1368315,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1621435172.1373563,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1621435172.1376226,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0519 14:39:32.137605       1 leaderelection.go:243] attempting to acquire leader lease  operators/8fa65150.coreos.com...
I0519 14:39:32.143465       1 leaderelection.go:253] successfully acquired lease operators/8fa65150.coreos.com
{"level":"info","ts":1621435172.1436667,"logger":"controller","msg":"Starting EventSource","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding","source":"kind source: /, Kind="}
{"level":"info","ts":1621435172.2441118,"logger":"controller","msg":"Starting Controller","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding"}
{"level":"info","ts":1621435172.244153,"logger":"controller","msg":"Starting workers","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding","worker count":1}
{"level":"info","ts":1621436719.492417,"logger":"controllers.ServiceBinding","msg":"Reconciling","serviceBinding":"test/busybox-postgresql","sb":{"apiVersion":"binding.operators.coreos.com/v1alpha1","kind":"ServiceBinding","namespace":"test","name":"busybox-postgresql"}}
{"level":"info","ts":1621436720.3018339,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"test/busybox-postgresql","retry":false,"error":null}

```
</details>
