### ISSUE TITLE
User and password from secret can't be evaluated

### ISSUE THREAD

**Issue by wangjsty** [redhat-developer/service-binding-operator#982]
### What is the environment (Minikube, Openshift)?
Openshift

### What is the SBO version used?
SBO 0.7.1

### What are the steps to reproduce this issue?
  1. Follow the sample guide: https://github.com/redhat-developer/service-binding-operator/blob/master/examples/nodejs_postgresql/README.md
  2.  But apply ServiceBinding by the follows for some custom environment variables:
  ```yaml
  apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  bindAsFiles: false
  application:
    name: nodejs-app
    group: apps
    version: v1
    resource: deployments
  services:
  - group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    name: db-demo
    id: postgresDB
  mappings:
  - name: DATABASE_DBCONNECTIONIP
    value: "{{ .postgresDB.status.dbConnectionIP }}"
  - name: DATABASE_DBCONNECTIONPORT
    value: "{{ .postgresDB.status.dbConnectionPort }}"
  - name: DATABASE_SECRET_USER
    value: "{{ .postgresDB.status.dbCredentials.user }}"
  - name: DATABASE_SECRET_PASSWORD
    value: "{{ .postgresDB.status.dbCredentials.password }}"
  - name: DATABASE_DBNAME
    value: "{{ .postgresDB.status.dbName }}"
  ```

### What is the expected behaviour?
All custom environment variables are evaluated successfully.

### What is the actual behaviour?
The user and password can't be evaluated by the error of"can't evaluate field password in type interface {}"

### Service Binding Operator Logs
{"level":"info","ts":1623944812.7547207,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"service-binding-demo/binding-request","retry":false,"error":"template: mappings:1:14: executing \"mappings\" at <.postgresDB.status.dbCredentials.user>: can't evaluate field user in type interface {}"}
{"level":"info","ts":1623944812.804421,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"service-binding-demo/binding-request","retry":false,"error":"template: mappings:1:14: executing \"mappings\" at <.postgresDB.status.dbCredentials.password>: can't evaluate field password in type interface {}"}

### Additional Information (Screenshots, etc)

CRD databases.postgresql.baiju.dev:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    service.binding/db.host: path={.status.dbConfigMap},objectType=ConfigMap
    service.binding/db.name: path={.status.dbConfigMap},objectType=ConfigMap
    service.binding/db.password: path={.status.dbConfigMap},objectType=ConfigMap
    service.binding/db.port: path={.status.dbConfigMap},objectType=ConfigMap
    service.binding/db.user: path={.status.dbConfigMap},objectType=ConfigMap
    service.binding/dbConnectionIP: path={.status.dbConnectionIP}
    service.binding/dbConnectionPort: path={.status.dbConnectionPort}
    service.binding/dbName: path={.spec.dbName}
    service.binding/password: path={.status.dbCredentials},objectType=Secret
    service.binding/user: path={.status.dbCredentials},objectType=Secret
```
Database resource:
```yaml
apiVersion: v1
items:
- apiVersion: postgresql.baiju.dev/v1alpha1
  kind: Database
  ...... skip some lines ......
  spec:
    dbName: db-demo
    image: docker.io/postgres
    imageName: postgres
  status:
    dbConfigMap: db-demo
    dbConnectionIP: 172.30.58.28
    dbConnectionPort: 5432
    dbCredentials: db-demo-postgresql
    dbName: db-demo
```
