### ISSUE TITLE
SERVICE_BINDING_ROOT env variable is defined twice in the deployment

### ISSUE THREAD

**Issue by feloy** [redhat-developer/service-binding-operator#983]
### What is the environment (Minikube, Openshift)?

Kubernetes 1.20.6

### What is the SBO version used?

0.8.0

### What are the steps to reproduce this issue?

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: otherapp
spec:
  selector:
    name: otherapp
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_PASSWORD
          value: foobar
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: data
          - mountPath: /var/run/postgresql
            name: run
      volumes:
      - name: data
        emptyDir: {}
      - name: run
        emptyDir: {}
---

apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: asbr
spec:
  application:
    group: apps
    version: v1
    resource: deployments
    name: myapp
  bindAsFiles: true
  detectBindingResources: true
  services:
  - group: ""
    version: v1
    kind: Service
    name: otherapp
    namespace: bug1
EOF
```

### What is the actual behaviour?

```
$ kubectl get deployment myapp -o yaml 
[...]
    spec:
      containers:
      - env:
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        - name: SERVICE_BINDING_ROOT
          value: /bindings
```

### Additional Information (Screenshots, etc)
This can cause problem especially in `odo` when trying to update the deployment:

```
Failed to create manager for existing fields: failed to convert new object (apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="runtime"].env: duplicate entries for key [name="SERVICE_BINDING_ROOT"]
```
