### ISSUE TITLE
How to reference data from Secret that has generated name based on spec data.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#991]
Let's say that I have CR the one that Crunchy PostgreSQL uses.

```yaml
        apiVersion: crunchydata.com/v1
        kind: Pgcluster
        metadata:
          annotations:
            current-primary: hippo
          labels:
            crunchy-pgha-scope: hippo
            deployment-name: hippo
            name: hippo
            namespace: pgo
            pg-cluster: hippo
            pgo-version: 4.7.0
          name: hippo
        spec:
          BackrestStorage:
            accessmode: ReadWriteMany
            matchLabels: ""
            name: ""
            size: 5Gi
            storageclass: ""
            storagetype: dynamic
            supplementalgroups: ""
          PrimaryStorage:
            accessmode: ReadWriteMany
            matchLabels: ""
            name: hippo
            size: 5Gi
            storageclass: ""
            storagetype: dynamic
            supplementalgroups: ""
          ReplicaStorage:
            accessmode: ReadWriteMany
            matchLabels: ""
            name: ""
            size: 5Gi
            storageclass: ""
            storagetype: dynamic
            supplementalgroups: ""
          ccpimage: crunchy-postgres-ha
          ccpimagetag: centos8-13.3-4.7.0
          clustername: hippo
          database: hippo
          exporterport: "9187"
          name: hippo
          namespace: pgo
          pgbadgerport: "10000"
          podAntiAffinity:
            default: preferred
          port: "5432"
          user: hippo
          userlabels:
            pgo-version: 4.7.0
```

Crunchy PosgtreSQL Operator automatically creates Secret containing user password. The Secret has a name that follows following  pattern `<clusterName>-<userName>-secret`.

I'm trying to add  annotation to the above CR that will tell SBO to expose the secret data.
I'm trying something like this:
```
            service.binding/dbcredentials: path={.spec.name}-{.spec.user}-secret,objectType=Secret
```
but this is not working.

What is a correct way to get data from the object which name is combination of multiple fields form CR spec?
