### ISSUE TITLE
processingPipeline.Process(&<service-binding-object>) doesn't always return the name of the secret.

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/service-binding-operator#998]
### What is the environment (Minikube, Openshift)?

Minikube

### What is the SBO version used?

v0.9.0

### What are the steps to reproduce this issue?

```
      apiVersion: redis.redis.opstreelabs.in/v1beta1
      kind: Redis
      metadata:
        name: myredis
      spec:
        redisExporter:
          enabled: true
          image: 'quay.io/opstree/redis-exporter:1.0'
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
        kubernetesConfig:
          image: 'quay.io/opstree/redis:v6.2'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 101m
              memory: 128Mi
            limits:
              cpu: 101m
              memory: 128Mi
          redisSecret:
            name: redis-secret
            key: password
          serviceType: LoadBalancer
        redisConfig: {}
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
```
 
```
      apiVersion: binding.operators.coreos.com/v1alpha1
      kind: ServiceBinding
      metadata:
        creationTimestamp: null
        name: redis-link
      spec:
        application:
          group: apps
          name: api-app
          resource: deployments
          version: v1
        bindAsFiles: true
        detectBindingResources: true
        services:
        - group: redis.redis.opstreelabs.in
          kind: Redis
          name: myredis
          version: v1beta1
      status:
        secret: ""
```
When deploying the above binding object, ` processingPipeline.Process(&<service-binding-object>)` sometimes doesn't return the name of the secret.

### What is the expected behaviour?

The function `processingPipeline.Process(&<service-binding-object>)` should always return the name of the secret if no error had occurred/returned.

### What is the actual behaviour?

Sometimes the `processingPipeline.Process(&<service-binding-object>)` doesn't return the secret's name.
